import streamlit as st

#st.title("dream 11 players")


teams = ['Bulgaria', 'Israel', 'Switzerland', 'Czech Republic',
         'West Indies', 'Canada', 'Ireland', 'Luxembourg', 'Hong Kong',
         'Singapore', 'Nepal', 'Malta', 'Denmark', 'Guernsey', 'Namibia',
         'Croatia', 'Gambia', 'Sri Lanka', 'Spain', 'Serbia', 'Philippines',
         'Netherlands', 'Argentina', 'England', 'Greece', 'Cayman Islands',
         'Sierra Leone', 'Samoa', 'France', 'Japan', 'Thailand', 'Malawi',
         'Hungary', 'St Helena', 'Vanuatu', 'Isle of Man', 'Bhutan',
         'Sweden', 'Qatar', 'Papua New Guinea', 'Austria', 'Panama',
         'Zimbabwe', 'India', 'South Africa', 'Mali', 'Gibraltar', 'Ghana',
         'Uganda', 'Cook Islands', 'Estonia', 'Oman', 'Finland', 'Romania',
         'Botswana', 'Belgium', 'Germany', 'Cyprus', 'United Arab Emirates',
         'Nigeria', 'Fiji', 'Australia', 'Mexico', 'Turkey', 'Belize',
         'Tanzania', 'Mozambique', 'Kenya', 'United States of America',
         'Indonesia', 'Lesotho', 'Cameroon', 'Bermuda', 'Scotland',
         'New Zealand', 'Italy', 'Norway', 'Ivory Coast', 'Jersey',
         'South Korea', 'Portugal', 'Pakistan', 'Bahrain', 'Saudi Arabia',
         'Maldives', 'Bangladesh', 'Eswatini', 'Kuwait', 'Malaysia',
         'Chile', 'Iran', 'Myanmar', 'Slovenia', 'Mongolia', 'ICC World XI',
         'Rwanda', 'Bahamas', 'Swaziland', 'Brazil', 'China', 'Costa Rica',
         'Seychelles', 'Cambodia']

venues = ['King George V Sports Ground, Castel',
         'Moara Vlasiei Cricket Ground',
         'Moara Vlasiei Cricket Ground, Ilfov County', 'Meersen, Gent',
         'Tikkurila Cricket Ground', 'Kerava National Cricket Ground',
         'Marsa Sports Club', 'Pierre Werner Cricket Ground',
         'Scott Page Field, Vinor', 'Brian Lara Stadium, Tarouba, Trinidad',
         'Sabina Park, Kingston, Jamaica',
         'Dubai International Cricket Stadium', 'Sharjah Cricket Stadium',
         'Sheikh Zayed Stadium', 'Adelaide Oval',
         'Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)',
         'Al Amerat Cricket Ground Oman Cricket (Ministry Turf 2)',
         'Bellerive Oval, Hobart', 'Bready Cricket Club, Magheramason',
         'Bready Cricket Club, Magheramason, Bready',
         'Brisbane Cricket Ground, Woolloongabba, Brisbane',
         'Castle Avenue, Dublin',
         'Central Broward Regional Park Stadium Turf Ground, Lauderhill',
         'Civil Service Cricket Club, Stormont',
         'Civil Service Cricket Club, Stormont, Belfast',
         'County Ground, Bristol', 'Goldenacre, Edinburgh',
         'Grange Cricket Club Ground, Raeburn Place, Edinburgh',
         'Harare Sports Club', 'ICC Academy, Dubai', 'Malahide, Dublin',
         'Melbourne Cricket Ground',
         'Nassau County International Cricket Stadium, New York',
         'National Cricket Stadium, Grenada', 'Sportpark Het Schootsveld',
         'Sportpark Westvliet, The Hague', 'The Village, Malahide',
         'The Village, Malahide, Dublin', 'Tolerance Oval',
         'Tony Ireland Stadium', 'Warner Park, St Kitts',
         'Zayed Cricket Stadium, Abu Dhabi', 'P Sara Oval',
         'Europa Sports Complex',
         'Arnos Vale Ground, Kingstown, St Vincent',
         'Grand Prairie Stadium, Dallas', 'Indian Association Ground',
         'Terdthai Cricket Ground',
         'Tribhuvan University International Cricket Ground, Kirtipur',
         'King George V Sports Ground',
         'Sportpark Het Schootsveld, Deventer',
         'Wanderers Cricket Ground, Windhoek',
         'Mladost Cricket Ground, Zagreb', 'YSD-UKM Cricket Oval, Bangi',
         'Gahanga International Cricket Stadium. Rwanda',
         'Integrated Polytechnic Regional Centre', 'Barabati Stadium',
         'Coolidge Cricket Ground, Antigua', 'Holkar Cricket Stadium',
         'Newlands', 'Pallekele International Cricket Stadium',
         'R Premadasa Stadium, Colombo', 'R.Premadasa Stadium, Khettarama',
         'Sophia Gardens, Cardiff', 'SuperSport Park',
         'The Wanderers Stadium', 'Wankhede Stadium',
         'Guernsey Rovers Athletic Club Ground, Port Soif',
         'National Sports Academy, Sofia', 'Bayer Uerdingen Cricket Ground',
         'Lisicji Jarak Cricket Ground', 'Yeonhui Cricket Ground, Incheon',
         'Daren Sammy National Cricket Stadium, Gros Islet, St Lucia',
         'Belgrano Athletic Club Ground, Buenos Aires',
         'Hurlingham Club Ground, Buenos Aires',
         'Sir Vivian Richards Stadium, North Sound, Antigua',
         'St Albans Club, Buenos Aires', 'St Georges Quilmes', 'Kingsmead',
         'Sydney Cricket Ground', 'The Rose Bowl', 'National Stadium',
         'Nigeria Cricket Federation Oval 1, Abuja',
         'Nigeria Cricket Federation Oval 2, Abuja',
         'Tafawa Balewa Square Cricket Oval, Lagos',
         'University of Lagos Cricket Oval',
         'Mission Road Ground, Mong Kok, Hong Kong',
         'Mulpani Cricket Ground', 'Faleata Oval No 2, Apia',
         'Maple Leaf North-West Ground, King City',
         'National Stadium, Hamilton', 'Prairie View Cricket Complex',
         'Sportpark Maarschalkerweerd, Utrecht',
         'White Hill Field, Sandys Parish',
         'Sano International Cricket Ground',
         'Gelephu International Cricket Ground', 'Udayana Cricket Ground',
         'University of Doha for Science and Technology', 'VRA Ground',
         'Bayuemas Oval, Kuala Lumpur', 'Terdthai Cricket Ground, Bangkok',
         'UKM-YSD Cricket Oval, Bangi',
         'Desert Springs Cricket Ground, Almeria',
         "Queen's Park Oval, Port of Spain", 'Svanholm Park, Brondby',
         'GB Oval, Szodliget',
         'Royal Brussels Cricket Club Ground, Waterloo',
         'Sao Fernando Polo and Cricket Club', 'Bulawayo Athletic Club',
         'Queens Sports Club, Bulawayo',
         'Gymkhana Club Ground, Dar-es-Salaam',
         'Sikh Union Club Ground, Nairobi', 'TCA Oval, Blantyre',
         'University of Dar-es-Salaam Ground', 'Simar Cricket Ground, Rome',
         'Amini Park', 'Amini Park, Port Moresby',
         'Independence Park, Port Vila', 'Kinrara Academy Oval',
         'College Field', 'Happy Valley Ground',
         'La Manga Club Bottom Ground', 'Roma Cricket Ground',
         'Indian Association Ground, Singapore',
         'West End Park International Cricket Stadium, Doha',
         'Providence Stadium, Guyana',
         'United Cricket Club Ground, Windhoek',
         'Zahur Ahmed Chowdhury Stadium',
         'Zahur Ahmed Chowdhury Stadium, Chattogram',
         'Kensington Oval, Bridgetown',
         'Maharashtra Cricket Association Stadium',
         'Vidarbha Cricket Association Stadium, Jamtha',
         'New Wanderers Stadium',
         'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
         'Greenfield International Stadium, Thiruvananthapuram',
         'Kensington Oval, Bridgetown, Barbados',
         "National Cricket Stadium, St George's, Grenada",
         'Saurashtra Cricket Association Stadium, Rajkot',
         'SuperSport Park, Centurion', 'Gucherre Cricket Ground',
         'Achimota Senior Secondary School B Field, Accra',
         'Entebbe Cricket Oval', 'Kyambogo Cricket Oval',
         'Lugogo Cricket Oval', 'Wanderers', 'Dreux Sport Cricket Club',
         'Santarem Cricket Ground', 'Gymkhana Club Ground, Nairobi',
         'GMHBA Stadium, South Geelong, Victoria',
         'Zhejiang University of Technology Cricket Field',
         'Kingsmead, Durban', "St George's Park, Gqeberha",
         'The Wanderers Stadium, Johannesburg', 'Brabourne Stadium',
         'Brisbane Cricket Ground, Woolloongabba', 'Eden Park',
         'Western Australia Cricket Association Ground',
         'Los Reyes Polo Club', 'ICC Academy', 'ICC Academy Ground No 2',
         'Eden Park, Auckland', 'Hagley Oval',
         'Himachal Pradesh Cricket Association Stadium',
         'JSCA International Stadium Complex',
         'Shere Bangla National Stadium, Mirpur',
         'The Rose Bowl, Southampton',
         'Gahanga International Cricket Stadium, Rwanda',
         'Ruaraka Sports Club Ground, Nairobi', 'Willowmoore Park, Benoni',
         'Gymkhana Club Ground', 'ICC Global Cricket Academy',
         'Mombasa Sports Club Ground', 'Wanderers Cricket Ground',
         'Edgbaston, Birmingham', 'Shere Bangla National Stadium',
         'M Chinnaswamy Stadium', 'Beausejour Stadium, Gros Islet',
         'County Ground', 'Edgbaston', 'Feroz Shah Kotla',
         'Kennington Oval', "Lord's",
         'Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa',
         'Mangaung Oval', 'Moses Mabhida Stadium', 'Old Trafford',
         'R Premadasa Stadium', 'Riverside Ground', 'Seddon Park',
         'Senwes Park', 'Sir Vivian Richards Stadium, North Sound',
         'Sophia Gardens', "St George's Park", 'Trent Bridge',
         'Westpac Stadium', 'Manuka Oval, Canberra', 'Sky Stadium',
         'University Oval', 'Providence Stadium',
         'Bermuda National Stadium',
         'Grange Cricket Club Ground, Raeburn Place',
         'Grange Cricket Club, Raeburn Place', 'Stadium Australia',
         'College Field, St Peter Port', 'Bellerive Oval',
         'Darren Sammy National Cricket Stadium, St Lucia', 'Eden Gardens',
         'Gaddafi Stadium, Lahore', 'National Stadium, Karachi',
         'Perth Stadium', 'Subrata Roy Sahara Stadium', 'Jade Stadium',
         'Bay Oval', 'Central Broward Regional Park Stadium Turf Ground',
         'Punjab Cricket Association Stadium, Mohali',
         'Sylhet International Cricket Stadium', 'Sabina Park, Kingston',
         'Sylhet Stadium', 'Warner Park, Basseterre',
         'Windsor Park, Roseau', 'Rangiri Dambulla International Stadium',
         'Saxton Oval', 'AMI Stadium', 'Bay Oval, Mount Maunganui',
         'Eden Gardens, Kolkata',
         'JSCA International Stadium Complex, Ranchi',
         'John Davies Oval, Queenstown', 'McLean Park, Napier',
         'Old Trafford, Manchester', 'Riverside Ground, Chester-le-Street',
         'Seddon Park, Hamilton', 'De Beers Diamond Oval',
         'Gaddafi Stadium', 'Sheikh Abu Naser Stadium',
         'Barsapara Cricket Stadium', 'Carrara Oval',
         'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
         'M.Chinnaswamy Stadium', 'Manuka Oval',
         'Punjab Cricket Association IS Bindra Stadium, Mohali',
         'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
         'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
         'Saurashtra Cricket Association Stadium',
         'Simonds Stadium, South Geelong',
         'Vidarbha Cricket Association Stadium, Jamtha, Nagpur',
         'Achimota Senior Secondary School A Field, Accra',
         'Sportpark Westvliet', 'Barsapara Cricket Stadium, Guwahati',
         'Solvangs Park, Glostrup', 'Buffalo Park',
         'M Chinnaswamy Stadium, Bengaluru',
         'Shaheed Veer Narayan Singh International Stadium, Raipur',
         'Sardar Patel Stadium, Motera', 'Barabati Stadium, Cuttack',
         'Holkar Cricket Stadium, Indore',
         'Maharashtra Cricket Association Stadium, Pune',
         'Narendra Modi Stadium', 'Sawai Mansingh Stadium, Jaipur',
         'Wankhede Stadium, Mumbai', 'Jinja Cricket Ground',
         'Headingley, Leeds', 'Khan Shaheb Osman Ali Stadium',
         'Tribhuvan University International Cricket Ground',
         'Hagley Oval, Christchurch', 'Desert Springs Cricket Ground',
         'Sportpark Maarschalkerweerd', 'Rawalpindi Cricket Stadium',
         'Queens Sports Club', 'Arun Jaitley Stadium, Delhi',
         'Shrimant Madhavrao Scindia Cricket Stadium, Gwalior',
         'Selangor Turf Club, Kuala Lumpur', 'McLean Park',
         'Windsor Park, Roseau, Dominica', 'Arnos Vale Ground, Kingstown',
         'Mission Road Ground, Mong Kok', 'United Cricket Club Ground',
         'Warner Park, Basseterre, St Kitts', 'La Manga Club Top Ground',
         'Trent Bridge, Nottingham', 'Kennington Oval, London',
         'University Oval, Dunedin', 'Hazelaarweg',
         'Rajiv Gandhi International Stadium, Uppal', 'Boland Park',
         'Green Park', 'MA Chidambaram Stadium, Chepauk',
         'Narendra Modi Stadium, Ahmedabad', 'Bready', 'OUTsurance Oval',
         'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
         'Himachal Pradesh Cricket Association Stadium, Dharamsala',
         'Arun Jaitley Stadium', 'Greenfield International Stadium',
         'Maple Leaf North-West Ground',
         'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
         'Sky Stadium, Wellington', 'M Chinnaswamy Stadium, Bangalore']

pitches = ["Green Pitch", "Dry Pitch", "Flat Track Pitch", "Dusty Pitch", "Wet Pitch", "Dead Pitch"]

allrounder = ['A Dizija', 'A Vala', 'AD Mathews', 'AR Patel', 'AV Lazarus', 'Aarif Sheikh', 'Aaron Jones',
              'Abdul Waheed', 'Aizaz Khan', 'Anshuman Rath', 'Aqib Ilyas', 'B Arora', 'B Ward', 'BA Pai', 'BA Stokes',
              'BFW de Leede', 'BJ Bennett', 'BJ McMullen', 'Basil Hameed', 'Bilal Tahir', 'C Campher', 'C Chatphaisan',
              'C Munro', 'C de Grandhomme', 'CG Williams', 'CJ Anderson', 'CJA Amini', 'CN Ackermann', 'CO Obuya',
              'DJ Hussey', 'DJG Sammy', 'DJM Short', 'DM de Silva', 'DS Airee', 'E Chigumbura', 'F Damiao Couana',
              'Faisal Khan', 'G Mckeon', 'GD Phillips', 'GJ Delany', 'H Carlyon', 'H Lakov', 'H Masakadza', 'HAM Shah',
              'HT Tector', 'Haider Butt', 'Hamza Dar', 'I Danladi', 'IO Okpe', 'Iftikhar Ahmed', 'Imran Anwar',
              'JA Morkel', 'JDP Oram', 'JDS Neesham', 'JE Root', 'JH Kallis', 'JJ Smit', 'JN Frylinck', 'JO Adedeji',
              'JO Holder', 'JP Duminy', 'K Nassoro', 'KA Pollard', "KC D'Souza", 'KD Shah', "KJ O'Brien",
              'KP Pietersen', 'KS Williamson', 'L Siaka', 'LJ Wright', 'LM Jongwe', 'LS Livingstone', 'M Campopiano',
              'M Levitt', 'MD Shanaka', 'MG Erasmus', 'MJ Clarke', 'MJ Santner', 'MM Ali', 'MN Waller', 'MNM Aslam',
              "MP O'Dowd", 'MR Adair', 'MR Swart', 'Mahmudullah', 'N Vanua', 'NA Greenwood', 'ND Laegsgaard',
              'NLTC Perera', 'Nizakat Khan', 'OH Agbomadzie', 'PM Seelaar', 'PR Surve', 'PW Borren', 'R Bakum',
              'R Powell', 'R Satheesan', 'R Shepherd', 'RA Jadeja', 'RG Mukasa', 'RK Paudel', 'RN Patel', 'RP Burl',
              'RR Patel', 'S Bau', 'S Davizi', 'S Muniandy', 'S Ravichandran', 'SA Ahmad', 'SC Williams', 'SKS Gill',
              'SO Ngoche', 'SPD Smith', 'SR Bhudia', 'SR Taylor', 'SR Watson', 'Sabbir Rahman', 'Sami Sohail',
              'Shadab Khan', 'Shahid Afridi', 'Shakib Al Hasan', 'Sikandar Raza', 'Sohail Ahmed', 'Soumya Sarkar',
              'TLW Cooper', 'TM Dilshan', 'Tilak Varma', 'V Ganesan', 'V Vijh', 'VP Thamotharam', 'Virandeep Singh',
              'W Barresi', 'W Madhevere', 'Waseem Muhammad', 'Yasim Murtaza', 'Yasir Ali', 'A Ashokan', 'A Mansale',
              'AD Russell', 'AK Markram', 'AM Tribe', 'AR Ramjani', 'Afif Hossain', 'Ayan Khan', 'Azyan Farhath',
              'B George', 'BRM Taylor', 'C Rububagumya', 'CH Gayle', 'CJ Chibhabha', 'CL White', 'CS MacLeod',
              'DJ Bravo', 'DJ Mitchell', 'DM Nakrani', 'DMW Rawlins', 'DR Smith', 'Faheem Nazir', 'GA Priandana',
              'GH Dockrell', 'GJ Maxwell', 'HH Pandya', 'IDM Latin', 'IK Gamantika', 'J Rasu', 'JD Ryder',
              'Janak Prakash', 'K Bhurtel', 'K Motlanka', 'K Waiswa', 'KIC Asalanka', 'KR Mayers', 'KS Leverock',
              'Kushal Malla', 'L Bruce', 'LMP Simmons', 'Luqman Butt', 'MA Leask', 'MD Gunathilaka', 'MN Samuels',
              'MP Stoinis', 'MR Marsh', 'MWR Stokes', 'Manpreet Singh', 'Meet Bhavsar', 'Mohammad Hafeez',
              'Muhammad Tanveer', 'N Nipiko', 'NS Dhaliwal', 'P Khadka', 'PD Collingwood', 'PR Stirling',
              'PWH de Silva', 'R Nehonde', 'RD Berrington', 'RG Sharma', 'RS Bopara', 'Riazat Ali Shah',
              'Rohan Mustafa', 'SB Styris', 'SK Raina', 'ST Jayasuriya', 'Sarfaraz Ali', 'Shoaib Malik', 'Syed Aziz',
              'TM Head', 'Taranjeet Singh', 'Umar Adam', 'V Kohli', 'V Saini', 'Yuvraj Singh', 'Zeeshan Maqsood',
              'TH David']

bowlers = ['A Bohara', 'A Busing-Volschenk', 'A Conteh', 'A Dutt', 'A Faletar', 'A Gbla', 'A Kalasi', 'A Khan',
           'A Limdawala', 'A Mene-Ejegi', 'A Nao', 'A Nathwani', 'A Natubhai Ahir', 'A Nehra', 'A Nel', 'A Nortje',
           'A Prashar', 'A Rangaswamy', 'A Turay', 'A Zampa', 'AA Rahayu', 'AAhan Achar', 'AB Agarkar', 'AC Botha',
           'ACF Stokes', 'AD Mascarenhas', 'AJ Hosein', 'AJ McKay', 'AJ Parmar', 'AM Kimote', 'AM Phangiso',
           'AN Hyobeom', 'AN Toube', 'AP Devcich', 'AR Adams', 'AR Cusack', 'AR McBrine', 'AU Rashid', 'AW Hawkins-Kay',
           'AY Patel', 'Abdul Majid Abbasi', 'Abdul Razzaq', 'Abdullah Akbarjan', 'Abdullah Jasat', 'Abdullah Mahmood',
           'Abdullah Rana', 'Abdullah Sheikh', 'Abdur Razzak', 'Abdur Rehman', 'Abul Farhad', 'Adil Butt',
           'Aditya Panwar', 'Adnan Idrees', 'Adnan Razzaq', 'Aftab Kayani', 'Ahmad Khalid Ahmadzai', 'Ahmadi Ravat',
           'Ahmadullah Shinwari', 'Ahmed Aqeel', 'Ahmed Baladraf', 'Ahsan Malik', 'Akhil Anil', 'Akhil Kumar',
           'Al-Amin Hossain', 'Ali Dawood', 'Ali Hasan', 'Ali Nayyer', 'Amal Jacob', 'Amandeep Singh', 'Amar Sharma',
           'Aminul Islam', 'Amir Farooq', 'Amir Hayat', 'Amjad Javed', 'Amjad Sher', 'Ammar Zuhdi Hazalan',
           'Amoluk Singh', 'Anik Ahmed', 'Anique Uddin', 'Arshad Iqbal', 'Ashiqullah Said', 'Ashwin Vinod',
           'Asif Bevinje', 'Ateeq Iqbal', 'Atif Kamal', 'Atif Mehmood', 'Atif-Ur-Rehman', 'Aung Ko Ko', 'Avi Dixit',
           'Ayush Ummat', 'Azam Khalil', 'Aziz Sualley', 'B Evans', 'B Ito-Davis', 'B Kumar', 'B Lee', 'B Masaba',
           'B Muzarabani', 'B Niaz', 'B Pondani', 'B Shikongo', 'B Siddharth', 'BAW Mendis', 'BD Glover', 'BJ Currie',
           'BK Stroud', 'BM Scholtz', 'BMAJ Mendis', 'BP Adapaka', 'BW Hilfenhaus', 'Baljit Singh', 'Bashir Shah',
           'Bilal Hassun', 'Bilal Khan', 'Bilal Muhammad', 'C Bah', 'C Hinze', 'C Karunaratne', 'C Kyewuta', 'C Udekwe',
           'CA Liyanage', 'CA Soper', 'CB Roposo', 'CE McConchie', 'CJ Gannon', 'CK Jasmat', 'CK Langeveldt',
           'CPPM Sadun', 'CRD Fernando', 'CT Mutombodzi', 'CV Varun', 'D Ahir', 'D Berthe', 'D Birrell', 'D Ganesh',
           'D Heyliger', 'D Jakiel', 'D Jansen', 'D Klein', 'D Maisuria', 'D Mullen', 'D Parashar', 'D Pretorius',
           'D Rawat', 'D Robson', 'D Suzuki', 'D Visser', 'D Wabwire', 'D Wiese', 'D Wotu', 'DA Blignaut',
           'DAS Gunaratne', 'DB Loic', 'DBL Powell', 'DC Delany', 'DC Smith', 'DE Martel', 'DG Blampied', 'DJ Hawoe',
           'DJ Hooda', 'DJ Turkich', 'DK Anefie', 'DKD Warnakulasuriya', 'DL Brangman', 'DL Vettori', 'DO Christian',
           'DR Hooper', 'DT Doram', 'DT Johnston', 'DT Tiripano', 'DV Macome', 'DW Steyn', 'Dane Leo',
           'Dawood Ahmadzai', 'Delawar Khan', 'Dhananjay Rao', 'E Frimpong', 'E Karimi', 'E Mathew', 'E Niyomugabo',
           'E Packard', 'E Rukiriza', 'E Sebareme', 'ED Silva', 'EJB Miles', 'EMDY Munaweera', 'Ehsan Khan',
           'Elan Talker', 'Elias Sunny', 'F Akankwasa', 'F Banunaek', 'F Clarke', 'F Mutua', 'F Nsubuga', 'F Stoman',
           'F Thorpe', 'FA Cossa', 'FJ Klaassen', 'Faheem Ashraf', 'Fakhrul Mohon', 'Fanyan Mughal', 'Fawad Alam',
           'Festus Benn', 'Fitri Sham', 'G Bakiweyem', 'G Motie', 'G Ngegba', 'G Sesay', 'GA Lamb', 'GD Elliott',
           'GDR Eranga', 'GE Mathurin', "GH O'Brien", 'GK Berg', 'GM Muthui', 'GP Meade', 'GP Swann', 'GT Taylor',
           'Gaurav Mishra', 'Gaurav Tiwari', 'Gayan Munaweera', 'Gershon Yusuf', 'Ghulam Ahmadi', 'Gulsan Jha',
           'H Bharadwaj', 'H Fennell', 'H Kinga', 'H Klazinge', 'H Lin Aung', 'H Rathod', 'H Ssenyondo', 'HA Chohan',
           'HJ Manenti', 'HMRKB Herath', 'HN Ya France', 'HS Baidwan', 'Harbhajan Singh', 'Harmeet Singh',
           'Hasan Mahmud', 'Hassan Mehmood', 'Hayatullah Niazi', 'Hisham Sheikh', 'I Asif', 'I Mugisha', 'I Takahashi',
           'I Tchakou', 'IC Simao', 'ID Matic', 'IK Pathan', 'IKEG Artawan', 'IKO Aboagye', 'IW Budiarta',
           'Ibrahim Jabarkhel', 'Ibrahim Rizan', 'Ijaz Hussain', 'Ikbal Hossain', 'Ilyas Ahmed', 'Imad Wasim',
           'Imran Ahmed Kaneez', 'Imran Tahir', 'Imran Yousaf', 'Iqbal Hussain', 'Irfan Ahmed', 'Ishtiaq Ahmad',
           'J Baguma', 'J Batinibulu', 'J Bulele', 'J Coetzee', 'J Edness', 'J Ghadiyali', 'J Hurley', 'J Jojo',
           'J Little', 'J Miyaji', 'J Sebanja', 'J Shaju', 'J Singye', 'J Sumerauer', 'J Tuffin', 'JA Burrows',
           'JA Duffy', 'JAM Henri', 'JAR Blain', 'JB Abega', 'JC Balt', 'JC Darji', 'JD Newton', 'JE Pitcher',
           'JE Scott', 'JEC Franklin', 'JF Chester', 'JF Mooney', 'JJ Bumrah', 'JJ Celestine', 'JJ Huo', 'JJ Nyambo',
           'JK Kamande', 'JK Vifah', 'JL Denly', 'JL Martel', 'JM Anderson', 'JM Davison', 'JM Vujinovich', 'JO Ngoche',
           'JQK Moala', 'JR Barry', 'JR Hazlewood', 'JT Smuts', 'Jaspreet Singh', 'Jaswinder Singh', 'Jobayer Hossen',
           'Joshua Asia', 'Junaid Aziz', 'Junaid Khan', 'Junaid Sheikh', 'K Cawte', 'K Fletcher', 'K Hinds',
           'K Irakoze', 'K Juma', 'K Kato-Stafford', 'K Klein', 'K Kubota', 'K Namchaikul', 'K Piet', 'K Vislapuu',
           'KB Ahir', 'KH Pandya', 'KJ Young', 'KK Dobell', 'KK Lin Thu', 'KMDN Kulasekara', 'KS Bagabena', 'KV Morea',
           'Kaleem Sana', 'Kaleemullah', 'Karma Dorji', 'Kashif Daud', 'Khalid Ahmadi', 'Khin Aye', 'Khizar Hayat',
           'Kuldeep Yadav', 'L Maphane', 'L Nyarko', 'L Sanogo', 'LA Burns', 'LA Simango', 'LC Le Tissier',
           'LH Rodrigues', 'LJ Myott', 'LL Tsotsobe', 'LM Gabriel', 'LN Oluoch', 'LN Rajbanshi', 'LS Barkania',
           'Lemar Momand', 'Luis Hermida', 'Luka Woods', 'Luo Shilin', 'M Abdulla', 'M Akayezu', 'M Choamba', 'M Dixit',
           'M Faheem', 'M Jele', 'M Khojbariya', 'M Koli', 'M Leporoporo', 'M Magagula', 'M Morkel', 'M Muralitharan',
           'M Mwamadi', 'M Pathirana', 'M Shahbaz Butt', 'M Taniyama', 'M Taylor', 'M Vandrasi', 'M Yunusu Issa',
           'MA Baig', 'MA Starc', 'MB Tambe', 'MC Sorensen', 'MD Dai', 'MDK Perera', 'MF Manjate', 'MG Bracewell',
           'MG Hunter', 'MGSM Fernando', 'MJ Humphreys', 'MJ Mason', 'MJ McClenaghan', 'MJG Rippon', 'MK Thakur',
           'ML Bojang', 'MM Patel', 'MMR Obili', 'MNR Cooray', 'MO Jones', 'MP Yadav', 'MPGT Ketiyage', 'MR Gillespie',
           'MRJ Watt', 'MS Diawara', 'Ma Qiancheng', 'Mahmad Data', 'Mehran Siasar', 'Merwais Shinwari',
           'Mohamed Fadiga', 'Mohamed Ishmath', 'Mohamed Mahfooz', 'Mohamed Miuvaan', 'Mohamed Shafeeq',
           'Mohameed Taiwo', 'Mohammad Aadil Alam', 'Mohammad Amir', 'Mohammad Asaduzzaman', 'Mohammad Ayaz',
           'Mohammad Irfan', 'Mohammad Nawaz', 'Mohammad Nawaz (3)', 'Mohammed Shami', 'Mohammed Siraj',
           'Mohsin Shabbir', 'Mudassar Bukhari', 'Muhammad Amir', 'Muhammad Burhan', 'Muhammad Jabir', 'Muhammad Murad',
           'Muhammad Siddiqui', 'Muhammet Kursat', 'Murid Ekrami', 'Musawar Shah', 'Mustafizur Rahman', 'N Advani',
           'N Dutta', 'N Gnanapragasam', 'N Salekar', 'N Thushara', 'NCK Liyanage', 'NH Ekanayake', 'NK Aneesh Kumar',
           'NK Patel', 'NL McCullum', 'NM Odhiambo', 'NR Johns-Wickberg', 'NSK Mehta', 'NT Ellis', 'NW Bracken',
           'Nader Zahadiafzal', 'Najjam Shahzad', 'Nasrulla Rana', 'Nasum Ahmed', 'Navdeep Saini', 'Naveed Ahmed',
           'Naveed Shahid', 'Nawaf Ahmed', 'Nilansh Keswani', 'Nimish Lathief', 'Noah Mead', 'Noman Amjad',
           'Nurudeen Ibrahim', 'Nyeing Cham Soe', 'O Issouf', 'O Muzondo', 'OD Hald', 'OGL Bascome', 'Omar Hayat',
           'P Ayoleyine', 'P Bhart', 'P Cabebula', 'P Dakainivanua', 'P Fernando', 'P Florin', 'P Gheewala',
           'P Jayawickrama', 'P Koech', 'P Kotoisuva', 'P Kumbhare', 'P Malav', 'P Sarraf', 'P Sharma', 'P Sua',
           'P Useni', 'PA van Meekeren', 'PD Blignaut', 'PF Gallagher', 'PJ Ongondo', 'PK Matautaava', 'PP Chawla',
           'PP Shaw', 'PS Roberts', 'PV Vuniwaqa', 'PVD Chameera', 'Paing Danu', 'Parveen Kumar', 'Pavandeep Singh',
           'Prashant Shukla', 'Pratik Singh Bais', 'Pyae Phyo Wai', 'Qamar Mushtaque', 'Qasim Anwar',
           'Qudratullah Mir Afzail', 'R Abdulkareem', 'R Ashwin', 'R Athapaththu', 'R Coker', 'R Dhiman', 'R Kalimuthu',
           'R McLaren', 'R Mondol', 'R Ngarava', 'R Parag', 'R Parkin', 'R Sakurano-Thomas', 'R Sandeep', 'R Thapliyal',
           'R Trumpelmann', 'RA Abolarin', 'RD Atangana', 'RD Chahar', 'RDB Ahir', 'RE van der Merwe', 'RG Aga',
           'RJ Harris', 'RJ Nicol', 'RJ Peterson', 'RJ Sidebottom', 'RJ Trott', 'RJG Palmer', 'RK Kiseto', 'RL Chase',
           'RM Koda', 'RML Taylor', 'RN Lewis', 'RR Sharan', 'RW Price', 'Raaz Mohammad', 'Rahat Ali', 'Rahman Ademi',
           'Rahmatullah Mangal', 'Raja Adeel', 'Ravi Bishnoi', 'Raza Hasan', 'Raza Iqbal', 'Rizwan Butt',
           'Rizwan Haider', 'Robert Raina', 'S Arachchige', 'S Badree', 'S Bhari', 'S Burdekin', 'S Chaudhary',
           'S Clarke', 'S Conteh', 'S Desungnoen', 'S Gill', 'S Godara', 'S Kushretha', 'S Mohan', 'S Nsubuga',
           'S Pradhan', 'S Prasanna', 'S Ravoka', 'S Rossi', 'S Simpson', 'S Siriotis', 'S Stanikzay', 'S Tabuisulu',
           'S Thakor', 'S Thanikaithasan', 'S Vasilakis', 'S Vijay Unni', 'S Waqas Ahmed', 'S Yeshi', 'SA Jumbe',
           'SA Okpe', 'SC Getkate', 'SE Bond', 'SF Tiai', 'SG Diaby', 'SH Johnson', 'SH Obed', 'SI Kamea', 'SJ Benn',
           'SJ Patel', 'SL Malinga', 'SM Nash', 'SM Pollock', 'SM Tupou', 'SMK Waththage', 'SMSM Senanayake',
           'SN Netravalkar', 'SO Tikolo', 'SP Gauchan', 'SPS Shikongo', 'SR Rocket', 'SS Pathirana', 'ST Yalimaiwai',
           'SU Halarnkar', 'SZ Vayani', 'Saber Zakhil', 'Sahir Naqash', 'Salman Nazar', 'Sami Ullah', 'Shafat Ali Syed',
           'Shafraz Jaleel', 'Shagharai Sefat', 'Shaheen Shah Afridi', 'Shahzeb Choudhry', 'Shakerullah Safi',
           'Shantanu Kaveri', 'Shashikant Laxman', 'Sher Sahak', 'Shiraz Khan', 'Shoaib Rafiq', 'Shoriful Islam',
           'Shunan Ali', 'Simi Singh', 'Sirajullah Khadim', 'Sufiyan Muqeem', 'Surya Anand', 'Syazrul Idrus',
           'Syed Aqeel Israr', 'Syed Maisam Ali', 'Syed Rasel', 'T Henderson', 'T Hewa', 'T Jamtsho', 'T Kahamker',
           'T Lungameni', 'T Munyonga', 'T Musekiwa', 'T Muzarabani', 'T Panyangara', 'T Phaswana', 'T Wangchuk',
           'T van der Gugten', 'TCW Veillard', 'TD Chaoana', 'TE Kane', 'TGJ Gruijters', 'TJ Murtagh', 'TK Lal',
           'TK Patel', 'TL Chatara', 'TM Macalou', 'TS Chisoro', 'Taher Muhammad', 'Tanwir Afzal', 'Taranjit Singh',
           'Tasaduq Hussain', 'Tashi Phuntsho', 'Taskin Ahmed', 'Thuya Aung', 'Toqeer Ahmad', 'Umair Qasim', 'Umar Gul',
           'Usman Arif', 'Usman Khalid', 'Usman Najeeb', 'V Baskaran', 'V Mitari', 'V Zimonjic', 'VD Adewoye',
           'VJ Kingma', 'VRB Arachchige', 'Vinay Ravi', 'W Behr', 'W Ngowhuad', 'W Peatfield', 'W Wotu', 'WAE Burton',
           'WB Rankin', 'WPUJC Vaas', 'WT Gavera', 'Wahab Riaz', 'Waheed Ahmed', 'Waji Ul Hassan', 'Waqar Abbasi',
           'Waqar Ali', 'Waqar Zalmai', 'Waseeq Ahmed', 'Washeem Abbas', 'Washington Sundar', 'XC Bartlett',
           'YM Nkanya', 'YS Chahal', 'Yasin Patel', 'Yasir Mehmood', 'Z Bimenyimana', 'Z Hoque', 'ZB Lion-Cachet',
           'ZGF Foulkes', 'Zafer Durmaz', 'Zaheer Zahiri', 'Zahoor Khan', 'Zain Ahmad', 'Zain Ali', 'Zain Ul Abidin',
           'Zaman Khan', 'Zong Yuechao', 'Zulfiqar Babar', 'A Andrews', 'A Flintoff', 'A Husain', 'A Kheterpal',
           'A Kirschbaum', 'A Martel', 'A Morris', 'A Nanda', 'A Orfila', 'A Reyes', 'A Turkmen', 'A Venkatesh',
           'A Wright', 'A Yon', 'AAP Rivero', 'AC Agar', 'AC Douglas', 'AC Evans', 'ADL Stokoe', 'AF Buurman',
           'AF Ifill', 'AG Cremer', 'AJ Turner', 'AJA Samuels', 'AL Stephen', 'AR Leo', 'AS Hansra', 'AS Mehmi',
           'ASF Sirah', 'AV Lalcheta', 'Aakash Chand', 'Aamir Kaleem', 'Aamir Lal', 'Aayan Afzal Khan', 'Abbas Ghani',
           'Abdul Majid', 'Abdul Naser Baluch', 'Abdul-Shakoor Rahimzei', 'Abubacarr Kuyateh', 'Aftab Hussain',
           'Ahmad Raza', 'Ahmed Raza', 'Ahmed Wardak', 'Aizaz Cheema', 'Akhil Arjunan', 'Alam Nakash',
           'Alexandros Karvelas', 'Ali Abdulla Popalzae', 'Anas Khan', 'Anwar Rahman', 'Aqib Iqbal', 'Arafat Sunny',
           'Arjun Vinod', 'Aslam Mohammad', 'B Kgosiemang', 'B Khumalo', 'B Leo', 'B Mavuta', 'B Regmi', 'B Stanlake',
           'BDH Stevens', 'BV Vitori', 'Baz Aybui', 'Bilal Masud', 'Bilal Safdar', 'Bilal Zalmai', 'Bukhar Illikkal',
           'C Dickson', 'C Outerbridge', 'C Pengkumta', 'C Rumistrzewicz', 'C Viljoen', 'C Waiswa', 'C Wright',
           'CAJ Meschede', 'CD de Lange', 'CJ Boyce', 'CJ Langford', 'CJ McKay', 'CJPF Kalugamage', 'CM Akachukwu',
           'CN Greaves', 'CP Schofield', 'CW Perchard', 'D Abeyrathna', 'D Bishoo', 'D Dawa', 'D Dewald', 'D Marks',
           'D Muhumuza', 'D Mutu', 'D Polpitiya', 'D Ravu', 'D Sabir', 'DE Bollinger', 'DK Mathias', 'DK Shetty',
           'DM Richards', 'DN Wellalage', 'DNA Ankrah', 'DP Nannes', 'Danyal Raja', 'E Ernest', 'E Isaneez',
           'E Jabarkhel', 'E Otieno', 'E Schiferli', 'EB Ringera', 'F Choudary', 'F Khaliq', 'F Pieters',
           'Farzan Afzal', 'Fayaz Khan', 'Fayyaz Butt', 'Fazil Muhammad', 'G Fatouros', 'G Stewart', 'GC Galanis',
           'GC Murtaza', 'GD Arta', 'GD Drummond', 'GF Gomes', 'GF Linde', 'GG Alta', 'GM Ntambalika', 'GO Sopinho',
           'GRD Munasinghe', 'Gagandeep Singh', 'Ghulam Abbas Butt', 'Gurpratap Singh', 'H Gori', 'H Patel', 'H Thaker',
           'HA Varaiya', 'HAG Madhushanka', 'HMCM Bandara', 'HV Mandhyan', 'Habib Khan', 'Hamid Mahmood', 'Hasan Cakir',
           'Haseeb Amjad', 'Hassan Khan Mohammad', 'Hein Zin Aung', 'Huzaifa Mohammed', 'I Elec', 'I Kamara',
           'I Ntirenganya', 'IG Holland', 'IM Farrell', 'Ibrahim Hassan', 'Ibrahim Nashath', 'Ikramullah Khan',
           'Imran Ameer', 'Imran Arif', 'Imran Khan (1)', 'Irfan Hafejee', 'Ismaila Tanba', 'Izatullah Dawlatzai',
           'J Botha', 'J Broad', 'J Danikula', 'J Evans', 'J Kariko', 'J Kila', 'J Mulder', 'J Perman', 'J Theron',
           'JB Reva', 'JC Archer', 'JD Nel', 'JJ van der Wath', 'JK Mukhiya', 'JL Tutty', 'JM Muirhead', 'JM Obando',
           'JOA Gordon', 'JR Hopes', 'JW Chilia', 'JWW Gardner', 'Jaspal Singh', 'Jaweed Sadran', 'Junaid Siddiqui',
           'K Christie', 'K Gilham', 'K Gore', 'K Mirpuri', 'K Senamontree', 'K Shivam', 'KA Maharaj', 'KAJ Roach',
           'KDA Lukies', 'KJ Abbott', 'KJ Ferrary', 'KJ Patel', 'KO Altamirano', 'KP Meiyappan', 'KS Airee', 'Karan KC',
           'Karanbir Singh', 'Khalid Zahid', 'Khawar Ali', 'L Denny', 'L Karlsson', 'L Shafeeg', 'L Sreekumar',
           'LA Dawson', 'LH Ferguson', 'LT Bichard', 'LV van Beek', 'Lucky Ali', 'M Aboagye', 'M Altankhuyag',
           'M Badenhorst', 'M Charlie', 'M Dale-Bradley', 'M Gogev', 'M Jansen', 'M Kpaka', 'M Mooketsi', 'M Ozturk',
           'M Podosky', 'M Syahadat Ramli', 'M Theekshana', 'M Zondeki', 'MA Aponso', 'MG Johnson', 'MH Yardy',
           'MJ Ansell', 'MK Anafie', 'MS Aulakh', 'MS Graham', 'MS Sinclair', 'MTMMJ Ave', 'MV Pavlovic', 'MW Machan',
           'Mahedi Hasan', 'Mehran Khan', 'Mohammad Asif', 'Mohammad Atif', 'Mohammad Ghazanfar', 'Mohammad Kamran',
           'Mohammad Nadeem', 'Mohammad Naveed', 'Mohammad Shahzad', 'Mohammed Nadeem', 'Mosaddek Hossain',
           'Muhammad Afis', 'Muhammad Fahim', 'Muhammad Farooq', 'Muhammad Moiz', 'Muhammad Nadir',
           'Muhammad Shoaib Ahmed', 'Muhammad Wafiq', 'Muhammed Turkmen', 'Musaddiq Ahmed', 'Muslim Yar',
           'Muzahir Raza', 'N Nuntarach', 'N Pokana', 'N Senamontree', 'NA Maiolo', 'NK Tiwari', 'NM Salonen',
           'NO Miller', 'NR Kumar', 'Nadeem Ahmed', 'Namgay Thinley', 'Naseem Shah', 'Naved-ul-Hasan',
           'Ngawang Thinley', 'Niv Nagavkar', 'OE Taylor', 'OEG Baartman', 'OJ Webster', 'OP Stone',
           'Omid Shafi Rahman', 'Osama Mahmood', 'P Aho', 'P Arrighi', 'P Buccimazza', 'P Byron', 'P Manning',
           'P Mishra', 'P Nedeljkovic', 'P Utseya', 'P Vekaria', 'PADLR Sandakan', 'PC Connell', 'PHKD Mendis',
           'PJ Cummins', 'PL Mommsen', 'PP Ojha', 'PV Naringrekar', 'Phon Bunthean', 'R Ankad', 'R Baaleri', 'R Dhakal',
           'R Hekure', 'R Panchal', 'R Ravindra', 'RM Haq', 'RM Hira', 'RM West', 'RMS Eranga', 'RN ten Doeschate',
           'ROC Dunka', 'RP Singh', 'RR Joshi', 'RT Lyons', 'Raag Kapur', 'Raza-ur-Rehman', 'Rizwan Cheema', 'S Crowie',
           'S Gasteratos', 'S Gooch', 'S Lamichhane', 'S Maduranga', 'S Murari', 'S Nadigotla', 'S Pillai', 'S Randiv',
           'S Ravikumar', 'S Rukmal', 'S Shrivastava', 'S Sola', 'S Tarawally', 'S Vashisht', 'S Wickramasekara',
           'S Williams', 'S di Bartolomeo', 'SCJ Broad', 'SJ Hughes-Pinan', 'SK Atai', 'SK Awiah', 'SM Sharif',
           'SMHH Aung', "SNJ O'Keefe", 'SP Narine', 'ST Finn', 'SVE Bharathi', 'SW Tait', 'Saad Bin Zafar',
           'Saeed Ajmal', 'Sagar Pun', 'Sahel Zadran', 'Sahil Chauhan', 'Sajad Ahmadzai', 'Sana Ullah', 'Sandeep Goud',
           'Sarawut Maliwan', 'Saud Munir', 'Serdar Burak Emir', 'Shahab Alam', 'Shahil Momin', 'Shakeel Ahmed',
           'Shakeel Ansar', 'Sheikh Rasik', 'Sheraz Sheikh', 'Shuvagata Hom', 'Sohail Tanvir', 'Sohel Patel',
           'Sompal Kami', 'Sufyan Mehmood', 'T Chopel', 'T Gwandu', 'T Nightingale', 'T Perera', 'T Rossi', 'T Shamsi',
           'T Taylor', 'T Thushara', 'T Tshose', 'T Vanuarua', 'TA Boult', 'TB Sole', 'TJG Pringle', 'TKP Rajapaksha',
           'TM Odoyo', 'TS Waqavakatoga', 'TT Bresnan', 'TW Dlamini', 'Tamoor Sajjad', 'Tanzim Hasan Sakib',
           'Tariq Aziz', 'Tejwinder Singh', 'Tian Sen Qun', 'U Shahid', 'Usman Shinwari', 'Utkarsh Jain', 'V Ateak',
           'V Khanduri', 'Vichanath Singh', 'Virendra Kumar', 'Vishil Patel', 'Vraj Patel', 'W Nalisa', 'WJ Cope',
           'WJ Malinda', 'WK McCallan', 'WP Masakadza', 'WSLK Narayana', 'WT Mubayiwa', 'Wang Qi', 'Waqas Ahmad',
           'Waqas Barkat', 'Yair Nagavkar', 'Yasir Arafat', 'Yves Cyusa', 'Z Burgess', 'Z Groenewald', 'Z Khan',
           'ZE Matsinhe', 'Zabiullah Zahid', 'Zahid Zadran', 'Zaker Taqawi', 'Zeeshan Kukikhel', 'A Alexander',
           'A Neill', 'A Sawyer', 'A Shukla', 'AA Noffke', 'Abdul Bashir', 'Abdul Samad', 'Adil Khan', 'Afif Khattak',
           'Ahmadschah Ahmadzai', 'Ahmed Hassan', 'Akramullah Malikzada', 'Ali Naqi', 'Amir Hamza', 'Ammar Khalid',
           'Assad Mehmood', 'Azri Azhar', 'B Kalki Kumar', 'B Karki', 'B Laughlin', 'BE Johnson', 'BJ Diamanti',
           'Bashar Khan', 'Bhargav Narasimha', 'C Connolly', 'C Olphert', 'C Pervez', 'CC Blake', 'CT Tremlett',
           'DR Briggs', 'E Leie', 'GA Stuurman', 'GB Brent', 'GC Tonge', 'GI Maiden', 'HF Gurney', "IE O'Brien",
           'Israr Khan', 'J Giyanani', 'J Stanigze', 'JA Turner', 'JD Unadkat', 'JJ Wright', 'JL de Mey', 'JT Darrell',
           'Jitesh Patel', 'Jubair Hossain', 'Junaid Siddique', 'K Govind', 'K Macheka', 'K Penjor', 'K Santokie',
           'KV Sharma', 'L Balaji', 'LS Baker', 'M Breban', 'M Kartik', 'M Walker', 'M de Lange', 'MA Parker',
           'MD Bates', 'ML Lewis', 'MM Iqbal', 'Mohammad Kashif', 'Mohammad Shahid', 'Mubeen Tariq', 'Muhammad Ansar',
           'Muhammad Jawadullah', 'Muhammad Musa', 'Muhammad Saqib', 'Muhammad Zaghlool', 'N Thailappan', 'N Tyagi',
           'Naveed Fakhr', 'O Gholami', 'Obed Yosef', 'Oliver Rowe', 'P Masih', 'P Negi', 'R Frylinck', 'R Sai Kishore',
           'R Sharma', 'RJ Akram', 'RP Meredith', 'RSK Samson', 'Rafaqat Ali', 'Robiul Khan', 'S Rana', 'S Tyagi',
           'S Vats', 'SC Meaker', 'SG Whittingham', 'SJ Harmison', 'SM Dhakal', 'SM Harwood', 'SS Kang', 'Sabir Ali',
           'Sajedul Islam', 'Santiago Duggan', 'Shahbaz Ahmed', 'Shayan Khan', 'Shoaib Ali', 'Surinder Singh',
           'T Mupariwa', 'TF van Woerkom', 'TO Carmichael', 'TZ Chataira', 'Taijul Islam', 'UKPW Kumaranayaka',
           'Usman Ali', 'Usman Rafiq', "W O'Rourke", 'WT Mashinge', 'Waleed Waqar', 'Yash Talati', 'Zahid Mahmood',
           'Zeeshan Abbas', 'A Ashok', 'A Denuwan', 'A Desai', 'A Martin', 'A Mishra', 'AQM Yako', 'AS Abioye',
           'Abrar Ahmed', 'Abul Hasan', 'Adnan Gondal', 'Adnan Syed', 'Ahmed Raid', 'Asad Ali', 'Aswad Khan',
           'B Geeves', 'B Schuster', 'BB Sran', 'Basir Ahamad', 'Bipin Kumar', 'CK Tshuma', 'D Gough', 'DK Butler',
           'DS Wesonga', 'DSK Madushanka', 'Dharmendra Manani', 'E Frosler', 'Ebadat Hossain', 'G Mubiru',
           'G Richardson', 'GJ McCarter', 'GW Aldridge', 'HC Overdijk', 'Hasan Murad', 'IDR Bradshaw', 'Iftikhar Anjum',
           'Ihsanullah', 'J Butler', 'J Matharu', 'J Prodehl', 'J Raubenheimer', 'J Thinley', 'JT Ball',
           'Joginder Sharma', 'K Dorji', 'K Lake', 'K Subramanian', 'K Tari', 'KC Hodsoll', 'KTGD Prasad',
           'Karthik Pillai', 'L Gharasim', 'L Ntanzi', 'LJ Woodcock', 'M Markande', 'M Prasidh Krishna',
           'M Pushpakumara', 'MB van Schelven', 'MS Crane', 'Mansoor Amjad', 'Mohammed Aslam', 'Mohsin Khan',
           'Murtaza Yamin', 'N Boje', 'N Magagula', 'NH Naureen', 'Nasir Aziz', 'Navid Abdollahpour', 'O Isesele',
           'Osman Khan', 'Owais Ahmed', 'P Awana', 'PDRL Perera', 'R Agamiire', 'RDM Leverock', 'RJ Ranpura',
           'Robiul Islam', 'Rumman Raees', 'S Aravind', 'S Biko', 'S Kaul', 'S Saeed', 'S Sandeep Warrier', 'SKW Kelly',
           'SM Boland', 'SR Clark', 'ST Gabriel', 'Sandeep Nair', 'Saqlain Sajib', 'Shahzaib', 'Sharif Asadullah',
           'Shohidul Islam', 'Sultan Ahmed', 'Sumon Khan', 'T Britton', 'T Kamungozi', 'T Natarajan', 'TC Vine',
           'TJ Draca', 'TL Chivanga', 'TU Deshpande', 'Tanvir Ahmed', 'Usman Khan', 'V Marghashayam', 'Waqas Maqsood',
           'YA Abdulla', 'Z Simpson', 'Zulqarnain Haider', 'BT Foakes', 'C Smith', 'CT Bancroft', 'Gabor Torok',
           'Imran Haider', 'JDA Richardson', 'JDP Albertze', 'K Lion-Cachet', 'L Kamarlekar', 'L Nakomo',
           'M Goonetilleke', 'MK Gnanasekaram', 'Muhaddis Muhaddis', 'N Henderson', 'NJA Smith', 'P Syafiq Ali',
           'Rayhaan Ahmed', 'S Qeshile', 'SE Aquilina', 'SI de Saram', 'Santiago Iturbe', 'Soochan Park', 'TR Ambrose',
           'W Jackson', 'Zeshan Arif']

wicketkeeper = ['A Athanaze', 'A Bhagwat', 'A Bushell', 'A Davidson Soler', 'A Govorko', 'A Halbhavi', 'A Ilaoa',
                'A Kadowaki Fleming', 'A Kainessie', 'A Kansonkho', 'A Kapoor', 'A Langham', 'A McAuley', 'A Nimaga',
                'A Osei', 'A Patmore', 'A Poulose', 'A Rajshekara', 'A Sarma', 'A Saud', 'A Sharma', 'A Shreshta',
                'A Tripathi', 'AA Onikoyi', 'AAA Patel', 'AB Barath', 'AC Gilchrist', 'AD Hales', 'AF Milne',
                'AGS Gous', 'AJ Finch', 'AJ Jabiri', 'AJ Mosca', 'AJ Strauss', 'AL Kerai', 'AN Kervezee', 'AN Petersen',
                'AP Rajeevan', 'AP Yadav', 'AR Patwa', 'ARA Chambers', 'AS Samra', 'AT Nidamanuru', 'AT Rayudu',
                'Aaftab Alam Khan', 'Aaqib Sulehri', 'Abdul Rahman', 'Abdul Shakoor', 'Abdul Shakoor (2)',
                'Abdul Stanikzai', 'Abdullah Shahid', 'Abhilash Patil', 'Abraash Khan', 'Abrar Bilal', 'Absar Khan',
                'Abu Zar', 'Adnan Ilyas', 'Aftab Ahmed', 'Agha Salman', 'Ahmed Faiz', 'Ahmer Bin Nisar',
                'Ainool Hafizs', 'Ainool Haqqiem', 'Akash Babu', 'Alfredo Puentes', 'Ali Naseer', 'Ali Raza',
                'Ali Saleem', 'Aman Desai', 'Aminullah Tanha', 'Amir Sharif', 'Amjad Ali', 'Anam Mollik',
                'Anamul Haque', 'Anjar Tadarus', 'Anser Mehmood', 'Ansh Tandon', 'Areeb Quadir', 'Ariful Haque',
                'Arshad Mazarzei', 'Arshdeep Singh', 'Arslan Amjad', 'Asad Mahmood', 'Asad Shafiq', 'Aslam Khan',
                'Aviel Warsulkar', 'Awais Ahmed', 'Azhar Andani', 'B Ivanov', 'B Namsrai', 'BA King', 'BAA Zammitt',
                'BB Chari', 'BC Sahin', 'BJ Davidson', 'BJ Watling', 'BKG Mendis', 'BLCS Kumara', 'BM Duckett',
                'BV Save', 'Babar Hayat', 'C Bisson', 'C Bogdanos', 'C Brennan', 'C Carter', 'C Cassell', 'C Chete',
                'C Hauptfleisch', 'C Jonker', 'C Kieswetter', 'C Madande', 'C Munoz-Mills', 'C Sudarsanan', 'C Tlali',
                'C Webster', 'CA Ingram', 'CA Lynn', 'CAK Walton', 'CC Machado', 'CD McMillan', 'CD Wallace',
                'CJ Bowes', 'CJ Ferguson', 'CJ Jordan', 'CJO Smith', 'CK Coventry', 'CK Kapugedera', 'CMW Read',
                'CP Turkich', 'CR Richards', 'CR Woakes', 'D Brevis', 'D Cleaver', 'D Doyle-Calle', 'D Ferreira',
                'D Foxcroft', 'D Khanal', 'D Long Martinez', 'D Marsic', 'D Mauro', 'D Nath', 'D Traore', 'D Wheatley',
                'D la Cock', 'DA Miller', 'DG Brownlie', 'DJ Willey', 'DK Dahani', 'DL Richards', 'DM Bravo',
                'DM Gondaria', 'DO Obuya', 'DP Hyatt', 'DR Tawake', 'DS Maraiwai', 'Danyal Akbar', 'Dharmang Patel',
                'Divyendra Singh', 'Dylan Steyn', 'E Dusingizimana', 'E Hasahya', 'E Haven', 'E Lewis', 'E Ul Haq',
                'EB Knowles', 'EJG Morgan', 'ES Szwarczynski', 'F Achelam', 'F Baleri', 'F Behardien', 'F Suluoto',
                'FA Allen', 'FA Klokker', 'FFJ Heo', 'FFZ Nhaduate', 'Fiaz Ahmed', 'G Gambhir', 'G Ganbold',
                'G Kansonkho', 'G Manan', 'G Schachat', 'G Singhdeo', 'G Thakur', 'GC Wilson', 'GJ Hopkins',
                'GJ Thompson', 'GM Hamilton', 'GM Strydom', 'GPK Wijesingha', 'GR Adair', 'GY Prastama',
                'Ghulam Shabber', 'H Niaz', 'H Srinivasan', 'HA Jackson', 'HD Rutherford', 'HDRL Thirimanne', 'HG Kuhn',
                'HG Munsey', 'HJ Jordaan', 'HM Nicholls', 'HS Gericke', 'Habib Ahmadzai', 'Hadisullah Tarakhel',
                'Haider Ali', 'Hammad Azam', 'Haris Rauf', 'Haris Sohail', 'Hasan Ali', 'Haseeb Ghafoor',
                'Haseebullah Khan', 'Hassan Rasheed', 'Hilal Ahmad', 'I Kaia', 'I Niyomugabo', 'IA De Silva',
                'IA Karim', 'II Selemani', 'IK Darmawan', 'IS Sodhi', 'Ibrahim Rahimi', 'Imran Ali Butt',
                'Imran Farhat', 'Irfan Khan', 'Irshad Mubbashar', 'Ishan Kishan', 'Ivan Splicevic', 'J Alegra',
                'J Baleicikoibia', 'J Bangura', 'J Barker', 'J Cama', 'J Fraser-McGurk', 'J Grassi', 'J Grzinic',
                'J Hansrod', 'J Jemison', 'J Kemp', 'J Liyanage', 'J Marples', 'J Mees', 'J Mosca', 'J Mubarak',
                'J Suleman', 'J Trembeath-Moro', 'J Vira', 'J West', 'JA Burns', 'JA Clarkson', 'JAD Lawrenson',
                'JC Buttler', 'JC Martin', 'JD Allan', 'JD Campbell', 'JE Dunford', 'JEA Doctora', 'JF Smith', 'JJ Roy',
                'JM Bairstow', 'JM Sharma', 'JN Malan', 'JN Mohammed', 'JOP Scamans', 'JP Bray', 'JP Inglis',
                'JP Kotze', 'JS Foster', 'JW Jenner', 'Jaker Ali', 'Jassim Khan', 'Javed Maroofkhail', 'Jubaid Ahamed',
                'Junaid Siddique', 'K Dasan', 'K Ghalley', 'K Mothlhanka', 'K Suttisan', 'KA Jadhav', 'KA Vimlesh',
                'KD Karthik', 'KDK Vithanage', 'KH Abe', 'KJ Coetzer', 'KL Rahul', 'KTK Rodrigo', 'Kamran Akmal',
                'Kamran Khan', 'Kaushal Kumar', 'Khalid Kail', 'Khalid Shah', 'Khizer Ahmed', 'Khurram Khan',
                'Khurram Nawaz', 'L Canessane', 'L Emilio', 'L Lamin', 'L Ronchi', 'L Tucker', 'L Vincent',
                'L Yamamoto-Lake', 'LA Collado', 'LA Dunbar', 'LD Chandimal', 'LI Salomone', 'LJ Barker', 'LRPL Taylor',
                'Luca Petre', 'M Beitaki', 'M Coetzee', 'M Cohen', 'M Klinger', 'M Machado', 'M Martin', 'M Mosehle',
                'M Shumba', 'M Sohel Patel', 'M Thurgate', 'M Vaik', 'M Worndl', 'MA Jones', 'MA Ouma', 'MB Kruger',
                'MD Patel', 'MDKJ Perera', 'MEK Hussey', 'MH Oman', 'MJ Guptill', 'MJ Hay', 'MJ Prior', 'MK Pandey',
                'MK Tiwary', 'ML Hayden', 'MO Kitunda', 'MP Biddappa', 'MP Breetzke', 'MW Short', 'Mabsar Abdulla',
                'Mahmudul Hasan Joy', 'Mamoon Latif', 'Manan Ali', 'Mandeep Singh', 'Mario Ovalle', 'Mian Mehmood',
                'Mirza Baig', 'Misbah-ul-Haq', 'Mohamed Arief', 'Mohammad Boota', 'Mohammad Haris', 'Mohammad Ihsan',
                'Mohammad Mithun', 'Mohammad Naim', 'Mohammad Rizwan', 'Mohammad Yousuf', 'Mohammed Qasim',
                'Muhammad Amin', 'Muhammad Kaleem', 'Muhammad Muneeb', 'Muhammad Saleem', 'Muhammad Umar',
                'Muhammad Usman', 'Muhammad Yasin', 'Mukhtar Ahmed', 'Mukhtar Ghulami', 'Mushfiqur Rahim',
                'Mustafa Omer', 'Myat Thu Aung', 'N Acawei', 'N Davin', 'N Dickwella', 'N Khanna', 'N Knights',
                'N Mapunda', 'N Pooran', 'NA Rock', 'NG Jones', 'NL Smith', 'NM Coulter-Nile', 'NRJ Croes', 'NS Poonia',
                'NT Broom', 'Nasir Hossain', 'Nasir Jamshed', 'Nay Lin Htun', 'Nazmus Sakib', 'Nurul Hasan',
                'O Olaleye', 'OA Shah', 'OF Smith', 'Omair Yousuf', 'Ousman Bah', 'P Dhiman', 'P Hatchman', 'P Kurup',
                'P Murungi', 'P Sadev', 'P Silas', 'P Suanchuai', 'P Yevugah', 'P Zuze', 'PA Patel', 'PB Gouge',
                'PD Salt', 'PG Fulton', 'PJ Ingram', 'PJ Moor', 'PM Nevill', 'Pratik Agnihotri', 'Puneet Arora',
                'R Escobar', 'R Mutumbami', 'R Sandaruwan', 'R Tari', 'RA Bhatti', 'RA Tripathi', 'RB Patel',
                'RD Gaikwad', 'RD McCann', 'RE Levi', 'RK Singh', 'RM Siri', 'RR Bastiansz', 'RR Hendricks', 'RR Pant',
                'RR Rossouw', 'RS Morton', 'RT Ponting', 'RWT Key', 'Rafiullah', 'Raqibul Hasan',
                'Rasheed Ali Mamadkhel', 'Rashid Hashmi', 'Ravinder Singh', 'Ritik Tomar', 'Rohail Nazir',
                'Rohit Kumar', 'S Austin', 'S Chophel', 'S Cotter', 'S Dube', 'S Elayaperumal', 'S Grover', 'S Hook',
                'S Houghton', 'S Jele', 'S Jora', 'S Kimura', 'S Loday', 'S Matsikenyeri', 'S Natsagdorj',
                'S Navaratne', 'S Periyalwar', 'S Rungrueang', 'S Samal', 'S Samarawickrama', 'S Santhirakumaran',
                'S Sesazi', 'S Smith', 'S Srikanth', 'S Udhayan', 'SA Edwards', 'SA Wijeratne', 'SA Yadav', 'SD Hope',
                'SE Marsh', 'SHT Kandamby', 'SJ Baard', 'SJ Myburgh', 'SL Perera', 'SM Curran', 'SN Pathirana',
                'SR Mukkamalla', 'SS Cottrell', 'SS Iyer', 'ST Doheny', 'SW Billings', 'Saad Khan', 'Sachin Mandy',
                'Sahibzada Farhan', 'Saim Ayub', 'Salman Butt', 'Samiallah Khalil', 'Saqlain Ali', 'Sarfraz Butt',
                'Sathya Narayanan', 'Seetharam Guruvayoorappan', 'Selim Salau', 'Shadnan Khan', 'Shafiq Sharif',
                'Shahbaz Badar', 'Shaheryar Butt', 'Shahid Arshad', 'Shahid Wasif', 'Shahzaib Hasan', 'Shahzaib Jamil',
                'Shaiman Anwar', 'Shamim Hossain', 'Shamsur Rahman', 'Shaof Hassan', 'Shayan Jahangir', 'Shehzad Patel',
                'Sherul Mehta', 'Shoaib Khan', 'Shubman Gill', 'Simandeep Singh', 'Simon Shalders', 'Sulaimon Runsewe',
                'Suraj Kumar', 'Swann Htet Ko Ko', 'Syed Haider', 'Syed Rehmatullah', 'T Bavuma', 'T Bharaj',
                'T Marumani', 'T Sandeep', 'T Sumiya', 'TA Blundell', 'TB de Bruyn', 'TC Barker', 'TD Paine',
                'TG Southee', 'TK Joseph', 'TK Musakanda', 'TN de Grooth', 'TP Visee', 'TR Birt', 'TS Kamunhukamwe',
                'TSS Mackintosh', 'TWM Latham', 'Talha Khan', 'Tamim Iqbal', 'UNGB Thenannahelage', 'Umar Amin',
                'Umer Imtiaz', 'Usman Khan', 'Usman Patel', 'V Aravind', 'V Hristov', 'V Jagannivasan', 'V Shetty',
                'V Sibanda', 'VS Padhaal', 'Vinay Iyer', 'W Boshoff', 'W Miyauchi', 'WA Young', 'WG Jacks',
                'WIA Fernando', 'Wahidullah Sahak', 'Waqar Khan', 'Waqar Ul Hassan', 'Wei Guo Lei', 'Y Jalloh',
                'Y Naing Tun', 'Y Saranonnakkun', 'YBK Jaiswal', 'YJC Altamirano', 'Younis Khan', 'ZE Green',
                'Zaheer Ibrahim', 'Zakir Hasan', 'Zameer Khan', 'Zeeshan Ali', 'Zishan Shah', 'Zubaidi Zulkifle',
                'Zulqarnain Haider', 'A Bagai', 'A Balbirnie', 'A Bhadauria', 'A Ferguson', 'A Gorawara', 'A Johnmary',
                'A Manepalli', 'A Modi', 'A Mundra', 'A Mutreja', 'A Otwani', 'A Parima', 'A Randhawa', 'A Raza',
                'A Sharafu', 'AA Obanda', 'AB de Villiers', 'AD Algar', 'ADS Fletcher', 'AJ Ayannaike', 'AK Mohan',
                'AK Perera', 'AK Sah', 'AM Rahane', 'AN Cook', 'AR Berenger', 'AR Naidoo', 'AS Wright', 'AT Carey',
                'Aasif Sheikh', 'Abdul Hashim', 'Abdullah Khan Lodhi', 'Abdur Rahman Sudais', 'Abhishek Ahuja',
                'Ahmad Ramdoni', 'Ahmed Hassan', 'Ahmed Shehzad', 'Akbar Khan', 'Ali Zaheer', 'Amar Naeem',
                'Aminuddin Ramly', 'Anwar Arudin', 'Aritra Dutta', 'Asif Khan', 'Assad Borham', 'Azam Khan',
                'Azeem Nazir', 'B Bhandari', 'B Fitchet', 'B Kohler-Cadmore', 'B Vakatini', 'B Zuiderent', 'BA Simango',
                'BB McCullum', 'BBJL Perera', 'BI Dilruksha', 'BJ Haddin', 'BM Pecic', 'BN Cooper', 'BR Dunk',
                'BR McDermott', 'Babar Azam', 'Bosco Tuyizere', 'C Forbes', 'C Hartmann', 'C Pyle', 'C Tear', 'C Tommy',
                'C Trott', 'C Zhuwao', 'CB Ondoa', 'CN Kakuru', 'CN Onwuzulike', 'CP Rizwan', 'CR Brathwaite',
                'CR Ervine', 'CU Jayasinghe', 'CV Anto', 'Choudry Share Ali', 'D Gumyusenge', 'D Mongia',
                'D Ndikubwimana', 'D Ramdin', 'D Teinaki', 'D Uwimana', 'D Weston', 'DA Mehta', 'DA Warner',
                'DAP Darrell', 'DC Thomas', "DDP D'Silva", 'DF Watts', 'DJ Malan', 'DJ Reekers', 'DP Conway',
                'DPMD Jayawardene', 'DR Flynn', 'DR Martyn', 'DR Patankar', 'DS Smith', 'Devender Singh',
                'Dhiman Ghosh', 'Dhruv Jurel', 'Dipanjan Dey', 'E Otgonbayar', 'E Solomon', 'EC Joyce', 'F Mutizwa',
                'F du Plessis', 'FH Allen', 'FL Reifer', 'Faheem Nellancheri', 'Faisal Javed', 'Faisal Mubashir',
                'Fakhar Zaman', 'G Chaturvedi', 'G Malla', 'G Singh', 'GC Smith', 'GJ Bailey', 'GJ Snyman', 'GO Jones',
                'H Isorena', 'H Klaasen', 'H McAleer', 'H Upadhyay', 'HC Brook', 'HE van der Dussen', 'HGV Vare',
                'HH Gibbs', 'HJ Patel', 'HJH Marshall', 'HM Amla', 'Hamed Khan', 'Hammad Mirza', 'Hamza Khan',
                'Hamza Tariq', 'Huang Junjie', 'Humayun Kabir', 'Husnain Kabeer', 'Hwanhee Lee', 'I Liyanage',
                'I Mansaray', 'I Pandey', 'IDA Damarell', 'IR Bell', 'Idrees Ul Haque', 'Imal Zuwak', 'Imran Nazir',
                'Imrul Kayes', 'Ismaeel Zia', 'Ismail Ali', 'J Butler', 'J Charles', 'J Dzulfikar', 'J Pakhiaokajee',
                'J Smits', 'JD Freyone', 'JH Davey', 'JJ Atkinson', 'JM Cox', 'JM How', 'JM Kemp', 'JM Vince',
                'JN Loftie-Eaton', 'JN Snape', 'JNT Vare', 'JP Kaltapau', 'JR Philippe', 'Jahurul Islam', 'Jakob Gul',
                'Jatinder Singh', "Jordan O'Brien", 'Junaid Mehmood', 'K Doriga', 'K Pala', 'K Rabada', 'K Tathgur',
                'KC Sangakkara', 'KD Kesuma', 'KF Bakiweyem', 'KH Prajapati', 'KJ Stagno', 'KM Jadhav', 'KNA Bandara',
                'KOA Powell', 'KW Richardson', 'Kashif Siddique', 'Khalid Latif', 'Kuldeep', 'Kuldeep Singh', 'L Ward',
                'LB Ferbrache', 'LE Bosman', 'LSP Siriwardene', 'Liton Das', 'Lokesh Bam', 'M Bhanuka', 'M Kasselman',
                'M Labuschagne', 'M Mariyappan', 'MA Carberry', 'ME Trescothick', 'MH Cross', 'MJ Lumb',
                'MJ Richardson', 'MN van Wyk', 'MPS Cheema', 'MS Dhoni', 'MS Wade', 'MV Boucher', 'Manan Bashir',
                'Manoj Adhikari', 'Mehedi Hasan Miraz', 'Mirza Ahsan', 'Mohamed Azzam', 'Mohammad Ahnaff',
                'Mohammad Amin', 'Mohammad Rizlan', 'Mohammad Salman', 'Mohammad Usman', 'Mohammad Wasim',
                'Moshiur Rahman', 'Muhammad Khan', 'Muhammad Safdar', 'Munim Shahriar', 'Munir Dar', 'Musa Shaheen',
                'Muzammil Shahzad', 'N Chejay', 'N Katechis', 'N Wijesekera', 'NG Collins', 'NJ Ferraby',
                'NJ Maddinson', "NJ O'Brien", 'Naseem Khushi', 'Nazmul Hossain Shanto', 'O Bascome', 'O Manishimwe',
                'O Tuyisenge', 'OB Nightingale', 'OE Newey', 'OK Mohamed', 'OO Bascome', 'OR Willis', 'P Abanda',
                'P Baron', 'P Bosnjak', 'P Chin', 'P Heron', 'P Khari', 'P Nissanka', 'PA Nixon', 'PA Raikes',
                'PBB Rajapaksa', 'PC de Silva', 'PD McGlashan', 'PJ van Biljon', 'PS Airee', 'PS Athavale',
                'Parvez Hossain Emon', 'Q de Kock', 'R Chopra', 'R Gaznavi', 'R Gowthaman', 'R Heyns', 'R Lutaaya',
                'R Mbaiwa', 'R Mupfudza', 'R Nath', 'R Obuya', 'R Pillai', 'R Sekaran', 'R Sheshadri', 'RA Sealy',
                'RA Thomas', 'RD Rickelton', 'RJMGM Rupasinghe', 'RR Behera', 'RV Uthappa', 'RW Chakabva',
                'Raja Shoaib', 'Rameez Shahzad', 'Ravinderpal Singh', 'Razmal Shigiwal', 'Rehman Abdul',
                'Rishad Hossain', 'Rizwan Mahmood', 'Rony Talukdar', 'S Ashwathnarayana', 'S Bangera', 'S Bogdos',
                'S Browne', 'S Chanderpaul', 'S Chandramohan', 'S Dhawan', 'S Ivetic', 'S Mathur', 'S Mba', 'S Movva',
                'S Sankar', 'S Singh', 'S Veerapathiran', 'SE Findlay', 'SJ Modani', 'SJS Smith', 'SKR Mallidi',
                'SM Davies', 'SM Katich', 'SO Hetmyer', 'SO Olayinka', 'SP Fleming', 'SP Gomes', 'SP Khakurel',
                'SP Patil', 'SP Terry', 'SR Mohan', 'SR Thompson', 'SS McKechnie', 'SSJ Brooks', 'SV Samson',
                'SW Poynter', 'Saad Nasim', 'Saghar Manzoor', 'Said Hakim', 'Saif Ullah Malik', 'Saim Hussain',
                'Sajid Cheema', 'Sameer Patel', 'Saqlain Haider', 'Sarfraz Ahmed', 'Saud Islam', 'Shan Masood',
                'Sharjeel Khan', 'Sivakumar', 'Sultan Ahmed', 'Syed Naqvi', 'Syed Tameem', 'T Banton', 'T Horpinitch',
                'T Kaisala', 'T Manders', 'T Maruma', 'T Mishra', 'T Rajiv', 'T Stubbs', 'T Suri', 'T Whiteman',
                'TC Bruce', 'TH David', 'TL Seifert', 'TP Ura', 'TS Fray', 'Tanzid Hasan', 'Towhid Hridoy',
                'Tshering Tashi', 'UT Khawaja', 'Ubaid Minhas', 'Umar Akmal', 'Umar Nawaz', 'Uzair Amir', 'V Aritharan',
                'V Mbazo', 'VB Chikkannaiah', 'VS Solanki', 'Virk Ali', 'W Niyitanga', 'WA Simpson', 'WKD Perkins',
                'WL Madsen', 'WTS Porterfield', 'WU Tharanga', 'WW Hinds', 'Wang Liuyang', 'Waqas Haider',
                'XM Marshall', 'Yasir Ali Chowdhury', 'Yusuf Bhoola', 'Zaid Soulat', 'Zain Asif', 'Zeeshan Khan',
                'Zhuang Zelin', 'Ziaur Rehman', 'NR Kumar', 'Asif Ali', 'MS Chapman', 'Naeem Gull', 'Tarun Sharma']

batter = ['A Bhargava', 'A Bhattarai', 'A Bishnoi', 'A Bulow', 'A Dananjaya', 'A Daxini', 'A Dhingra', 'A Djorovic',
          'A Gavde', 'A Johnson', 'A Khan', 'A Krishna', 'A Magdalenic', 'A Mehmood', 'A Mongar', 'A Ndlovu', 'A Paul',
          'A Sathyan', 'A Shahi', 'A Sokovagone', 'A Symonds', 'AA Banner', 'AA Jasani', 'AA Navicha', 'AB Dinda',
          'ACL Richards', 'AD Fofana', 'AD Poynter', 'AE Isesele', 'AG Prince', 'AJ Michael', 'AJ Redmond', 'AJ Staal',
          'AK Mandal', 'AK Muslar', 'AK Roger', 'AL Phehlukwayo', 'AM Blignaut', 'AM Ellis', 'AM Guruge', 'AM McCarthy',
          'AM Oyede', 'AM Patel', 'AN Aminou', 'AO Suji', 'AR Puri', 'AR White', 'AS Joseph', 'AT Chuvale',
          'Aamer Jamal', 'Aamer Yamin', 'Abbas Afridi', 'Abdul Wahid', 'Abdulla Bhoola', 'Abdullah Shafique',
          'Abhijeet Ahuja', 'Abhishek Sharma', 'Ahsan Abbasi', 'Ahsan Khan', 'Alex Carthew', 'Ali Khan',
          'Ali Mohammadipour', 'Ameel Mauroof', 'Ameer Saiyed', 'Amir Mangal', 'Amir Zaib', 'Amit Uniyal',
          'Amjad Mahboob', 'Ammad Uddin', 'Anasim Khan', 'Andrey Lilov', 'Ankit Dubey', 'Anmoldeep Singh', 'Anoop Orsu',
          'Anowarul Islam', 'Ansar Iqbal', 'Anthony Roe', 'Anwar Ali', 'Arafat Minhas', 'Asad Ali Rehemtulla',
          'Ashish Rana', 'Ashraful Shuvo', 'Asif Ali', 'Asif Iqbal', 'Awais Ikram', 'Azin Rafeeg', 'B Balala',
          'B Dugic', 'B Jerkovic', 'B Mahesh', 'B Maphosa', 'B Mejaro', 'B Wentzel', 'B White', 'B Williams', 'B Yadav',
          'BA Carse', 'BC Fortuin', 'BCJ Cutting', 'BE Hendricks', 'BG Lister', 'BJ McCarthy', 'BS Sandhu',
          'BS Stephenson', 'BTJ Wheal', 'Babar Ali', 'Bakhtiar Tahiri', 'Baljinder Singh', 'Baseer Khan', 'Ben Jones',
          'Benjamin Constanzo', 'Bhumeshswar Jagroo', 'C Brown', 'C Floyd', 'C Forshaw', 'C Liebenberg', 'C Roberts',
          'C Sakariya', 'C Smith', 'C Wickramasinghe', 'C Zavoiu', 'CA Keita', 'CA Young', 'CB Sole', 'CG Osborne',
          'CH Morris', 'CJ Delany', 'CM Rocca', 'CR Foggo', 'CR Suryawanshi', 'CS Baugh', 'CT Mumba', 'CV Harrison',
          'Charanjeet Singh', 'Chen Zhuo Yue', 'Cihan Altun', 'D Ajekun', 'D Cato', 'D Faletar', 'D Finau', 'D Ganga',
          'D Issiaka', 'D Jamyansuren', 'D Kansonkho', 'D Madushanka', 'D Myers', 'D Padikkal', 'D Paterson',
          'D Samarawickrama', 'D Siva Kumar', 'D Young', 'DAJ Bracewell', 'DC Stovell', 'DE Budge', 'DE Burgess',
          'DE Roache', 'DI Allan', 'DK Pallekonda', 'DKJ Claude', 'DL Chahar', 'DL Hemp', 'DLS van Bunge', 'DO Leicher',
          'DR Sams', 'DR Tuffey', 'DS Kulkarni', 'DS Vosloo', 'DT Christian', 'DV Devjani Mutreja', 'DV Varghese',
          'Danish Jasnaik', 'Delroy Leo', 'E Batkhuyag', 'E Kahamker', 'E Kubwimana', 'E Kuchey', 'E Samson',
          'E Walker', 'EC Rainsford', 'EF Beard', 'EHSN Silva', 'EP Thompson', 'Edward Taylor', 'Ehsan Nawaz',
          'Emran Shahbakhsh', 'F Hand', 'FH Edwards', 'FJ Mpegna', 'FL Patel', 'Fahad Tariq', 'Faisal Mehmood',
          'Faizan Asif', 'Faizan Mumtaz', 'Farhad Reza', 'Fayaz Mohammad', 'Fayyaz Ahmed', 'Fazil Rahman', 'G Axtell',
          'G Caisley', 'G Chohan', 'G Kaltongga', 'G Oliveira', 'G Riley', 'G Van Heerden', 'GE Gutierrez Chavez',
          'GEF Barnett', 'GG Banner', 'GH Bodi', 'GH Smit', 'GH Worker', 'GI Hume', 'GJ Batty', 'GK Ghalley',
          'GL Cloete', 'GSNFG Jayasuriya', 'GT Main', 'Garret Banner', 'Guillermo Aburto', 'Gurpreet Singh',
          'H Dandapani', 'H Davids', 'H Hajnic', 'H Hiri', 'H Ivanov', 'H Lin Oo', 'H Pieterse', 'H Pragji',
          'HB Kayondo', 'Hamza Tahir', 'Haroon Arshad', 'Haroon Mughal', 'Haroon Shahid', 'Harprit Singh',
          'Harry Johnson', 'I Katzarski', 'I Master', 'I Sharma', 'I Udana', 'IG Butler', 'IGTR Kumara', 'IH Romaine',
          'IJL Trott', 'IS Billcliff', 'Ibrahim Kursad Dalyan', 'Ignacio Lisboa', 'Imam-ul-Haq', 'Imran Haider',
          'Imran Khan', 'Ismail Sardar', 'Itibarshah Deedar', 'Izaz Ali', 'J Albin', 'J Anderson', 'J Buchanan',
          'J Chaturanga', 'J Chialoufas', 'J Clough', 'J Dickinson', 'J Drysdale', 'J Dunn', 'J Henry', 'J Hill',
          'J Horrocks', 'J Jarvis', 'J Louw', 'J Masquater', 'J Pant', 'J Reb', 'J Thomas', 'J Vijay', 'J Yon',
          'J van Heerden', 'JAH Marshall', 'JD Baker', 'JD Wildermuth', 'JDF Vandersay', 'JG Bethell', 'JH Mensah',
          'JJ Davidson', 'JJ Wright', 'JL Ontong', 'JL Pattinson', 'JM Iradukunda', 'JM Joao', 'JP Faulkner',
          'JRMVB Sanjaya', 'JS Jesani', 'JS Kundi', 'JT Brassell', 'Jahandad Khan', 'Jai Sinh', 'Jaikumar Thakur',
          'Jandu Hamoud', 'Jitin Singh', 'John Bartlett', 'Junaed Mullah', 'K Birkenstock', 'K Joshi',
          'K Kadowaki-Fleming', 'K Loday', 'K Mishara', 'K Modise', 'K Nima', 'K Thuchila', 'K Weeraratne',
          'KA Jamieson', 'KC Ramamoorthy', 'KD Mills', 'KDACK Gunarathne', 'KK Tillett', 'KM Awala', 'KM Dabengwa',
          'KM Jarvis', 'KM Venkataswamy', 'KMA Aziz', 'KMC Bandara', 'KO Meth', 'KO Otieno', 'KR Ebanks',
          'KS Lokuarachchi', 'Kamran Ahmadzai', 'Kamran Shazad', 'Kapil Kumar', 'Karweng NG', 'Kashif Abbas',
          'Kau Qalo', 'Kawsar Khan', 'Khaibar Deldar', 'Khan Arbaaz', 'Khurram Chohan', 'Khurram Manzoor',
          'Khushdil Shah', 'Kuldeep Lal', 'Kulwinderjeet Singh', 'L Berthe', 'L Botha', 'L Erdenebulgan',
          'L Monanthane', 'L Ngidi', 'L Sipamla', 'L Stubbs', 'L Zulu', 'LA Musiani', 'LA Pomersbach', 'LD Madushanka',
          'LE Plunkett', 'LF Muller', 'LHB Harrington-Myers', 'LJ Leokaoke', 'LKW Ezechiel', 'LN Onyango', 'LPC Silva',
          'LR Gaonkar', 'LW Potthoff', 'M Akhigbe', 'M Brasier', 'M Cope', 'M Fru', 'M Gouws', 'M Grzinic',
          'M Jobarteh', 'M Joseph', 'M Kadyan', 'M Kristensen', 'M Kyriacou', 'M Malle', 'M Montgomery', 'M Prasanna',
          'M Sarenac', 'M Sidibe', 'M Spoors', 'M Stanikzai', 'M Stoman', 'M Vivekanandan', 'MA Wood', 'MC Bascombe',
          'MC Henriques', 'MD du Preez', 'ME Leoela', 'MF Maharoof', 'MFI Assuncao', 'MJ North', 'ML Castillo',
          'MM Sarwar', 'MM Sharma', 'MM Siddique', 'MO Kain', 'MR Dorgan', 'MR Montfort', 'MS Atapattu', 'MS Chapman',
          'MS Diakite', 'MT Diaby', 'MV Matsau', 'MW Forde', 'Maaz Khan', 'Mahmud Jasat', 'Maidul Islam',
          'Manish Sharma', 'Mansoor Malangzai', 'Maqsood Ahmad', 'Mashrafe Mortaza', 'Masood Jayezeh', 'Mazhar Khan',
          'Mehrab Hossain jnr', 'Milad Momend', 'Milind Kumar', 'Mirza Ahmed', 'Mobashar Ashraf', 'Mofassar Saeed',
          'Mohamed Coulibaly', 'Mohamed Khan', 'Mohamed Rishwan', 'Mohamed Shiyam', 'Mohammad Ahsan',
          'Mohammad Hasnain', 'Mohammad Saifuddin', 'Mohammad Sami', 'Mohammad Tauqir', 'Mohammed Faraazuddin',
          'Mohammed Irshad', 'Mohsin Zaki', 'Mrittunjoy Chowdhury', 'Muhammad Kashif', 'Muhammad Tahir',
          'Muhammad Zafar Khan', 'Muhammed Manga', 'Muhammet Bicer', 'Mukesh Kumar', 'Murat Ipek', 'Murat Yilmaz',
          'Mustapha Yusuf', 'N Ahir', 'N Davidovic', 'N Deonarine', "N M'shangwe", 'N Master', 'N Mugabe', 'N Nankov',
          'N Naranbaatar', 'N Ndouteng', 'N Pathan', 'N Pradeep', 'N Rana', 'N Tanner', 'N Zimonjic', 'NA Janes',
          'NB Budayair', 'ND McKenzie', 'NE Bonner', 'NFI McCallum', 'NJ Reardon', 'NL Ujawe', 'NM Hauritz',
          'NMS Param', 'NN Odhiambo', 'NP Kenjige', 'Nadif Chowdhury', 'Naiem Bameri', 'Naseem Khan', 'Navid Balouch',
          'Nazakat Ali', 'Nazmul Hossain', 'Nazmul Islam', 'Nazril Rahman', 'Nazwan Ismail',
          'Nelson Jesus Navarrete Aburto', 'Nestor Dhamba', 'Nithish Kumar Reddy', 'Nooruddin Mujadady',
          'Noorullah Sidiqi', 'Nouman Butt', 'Nouman Sarwar', 'O Duff', 'O Lutbayar', 'OJ Hairs', 'OL Pitcher',
          'OSB Tilley', 'Omar Hussain', 'Omid Mailk Khel', 'Ovais Yousof', 'P Abhijit', 'P Campbell', 'P Deol',
          'P Gopalkrishnan', 'P Hingorani', 'P Kumar', 'P Mustard', 'P Pirabakaran', 'P Pustoslemsek', 'P Raho',
          'P Thongsa', 'PA Desai', 'PK Ananya', 'PK Dimitri', 'PL Bruno', 'PM Liyanagamage', 'PM Siddle', 'PWA Mulder',
          'Pargat Singh', 'Parvez Rasool', 'Parvindar Kumar', 'Prasad Anish', 'Pratis GC', 'Praveen Santhanakrishnan',
          'Qadeer Ahmed', 'Qasim Akram', 'R Dravid', 'R Galgalikar', 'R Goodwin', 'R Klein', 'R Kumar', 'R Mangal',
          'R Mazumder', 'R Pathan', 'R Rampaul', 'R Rohan', 'R Sharma', 'R Siriwardena', 'R Telemachus',
          'R Vinay Kumar', 'RA Reifer', 'RAJ Smith', 'RAS Lakmal', 'RHO Saunders', 'RI Ahmed', 'RJ Campbell',
          'RJ Hatchman', 'RJ Kirtley', 'RJW Topley', 'RL Bhudia', 'RLB Rambukwella', 'RM Dorji', 'RP Arnold',
          'RP Magar', 'RP Mitchell', 'RR Watson', 'RV Viraj', 'RW Hartley', 'Rajab Hussain', 'Rajkumar Rajendran',
          'Rakibul Hasan', 'Ramandeep Singh', 'Rameez Khan', 'Rameez Raja (2)', 'Rehan Ahmed', 'Rhys Burinaga',
          'Riyaz Kajalwala', 'Rohan Bhavesh Patel', 'Rubel Hossain', 'S Badrinath', 'S Banamali', 'S Bodha', 'S Delai',
          'S Dhakal', 'S Dhaniram', 'S Draunivudi', 'S FouchÃ©', 'S Franklin', 'S Gantulga', 'S Jamil', 'S Kamate',
          'S Kollery', 'S Koppolu', 'S Kubheka', 'S Mills', 'S Ogundipe', 'S Pitabeddara', 'S Sheelan', 'S Sreesanth',
          'S Tobgay', 'S Vijayakumar', 'S Weleilakeba', 'SA Engelbrecht', 'SA Mohandas', 'SB Wagh', 'SC Kuggeleijn',
          'SD Outerbridge', 'SE Rutherford', 'SF Mire', 'SI Mahmood', 'SK Patel', 'SM Sharma', 'SM Warnakulasuriya',
          'SMA Priyanjan', 'SN Thakur', 'SRMJJ Arachchilage', 'SSB Magala', 'SSM Stanislaus', 'SYS Assegon',
          'Sachin Kumar', 'Saif Hassan', 'Sajid Liaqat', 'Sajid Patel', 'Sapan Mehta', 'Saqib Naveed', 'Saqib Zulfiqar',
          'Saran Aslam', 'Sayed Monib', 'Sazib Bhuiyan', 'Sazzad Hosen', 'Sefu Athumani', 'Shafiul Islam',
          'Shah Abrar Hussain', 'Shahadat Hossain', 'Shahid Mahmood', 'Shahnawaz Dhani', 'Shaik Basha', 'Shariz Ahmad',
          'Sharveen Surendran', 'Shoaib Akhtar', 'Shoaib Khan jnr', 'Sidhant Singh', 'Sikander Zulfiqar',
          'Sikder Billah', 'Sohaib Maqsood', 'Sohail Ahmad', 'Sohail Khan', 'Sukhkaran Sahi', 'Sulaiman Ali',
          'Suman Ghimire', 'Syed Amanullah', 'T Amarmend', 'T Batjargal', 'T Brown', 'T Cross', 'T Filer', 'T Hinds',
          'T Martin', 'T Misi', 'T Singye', 'T Takada', 'T Tumursukh', 'T Turan', 'TAM Siriwardana', 'TAW Patterson',
          'TB Robinson', 'TCR Kimber', 'TG Gordon', 'TJ Ramphoma', 'TJ Stephenson', 'TK Curran', 'TM Dowlin',
          'TP Allen', 'TS Mills', 'TW Samuels', 'Tanveer Ahmed', 'Tanvir Islam', 'Tanzeel Sheikh', 'Tarun Sharma',
          'Tarun Yadav', 'Tayyab Tahir', 'Tenjin Rabgey', 'Tenzin Wangchuk jnr', 'U Aryaman Sunil', 'U Bhagwan',
          'U Bhatti', 'U Dorji', 'U Sofi', 'US Hathinjar', 'Umair Ali', 'Umair Sharif', 'Umair Tariq', 'Usama Mir',
          'Usman Mushtaq', 'Usman Qadir', 'Usman Waheed', 'V Jayant', 'V Sehwag', 'V Sukumaran', 'V Zanko',
          'VB van Jaarsveld', 'VD Philander', 'VE Tembo', 'VF Bomnyuy', 'VL Mukesh', 'VM Nyauchi', 'VR Iyer',
          'VS Wategaonkar', 'VV Morea', 'Vikramjit Singh', 'Vimal Kumar', 'W Maximo', 'W McClintock', 'W Perchard',
          'W Uisuk', 'WD Parnell', 'WJR Robertson', 'WK Bitis', 'Wahidullah Usmani', 'Waleed Rana', 'Walid Ghauri',
          'Waqas Ali', 'Waqas Khan', 'Waseem Yaqoob', 'XJ Doherty', 'Y Cariah', 'Y Konate', 'YK Pathan', 'YYM Jakda',
          'Yasar Haroon', 'Yasir Shah', 'Yin Chenhao', 'Yousef Shadzehisarjou', 'Yousif Wali', 'Yusuf Ebrahim',
          'Z Abbasi', 'Z Makadji', 'Z McLaughlin', 'Z Shurentsetseg', 'ZK Shem', 'ZM Tribe', 'ZR Jaboneke',
          'ZXM Vukusic', 'Zahid Khan', 'Zahir Mohammed', 'Zaki Ul Hassan', 'Zeeshan Sarwar', 'Zeeshan Siddiqui',
          'Zhao Tianle', 'Ziaur Rahman', 'Zohaib Sarwar', 'Zou Kui', 'Zuhaib Zubair', 'Zuhair Muhammad', 'A Ahmadhel',
          'A Amado', 'A Chaubey', 'A Chaudhary', 'A Donovan', 'A Dowling', 'A Gasteratos', 'A Karn', 'A Kaul',
          'A Maheshwari', 'A Manousis', 'A Nagarajan', 'A Pusthay', 'A Shahzad', 'A Shukla', 'A Simelane', 'A Valthapa',
          'AA Gajic', 'AA Hussein', 'AA Paradkar', 'AAP Atkinson', 'AB Kamara', 'AB Mengoumou', 'AC Voges', 'AE Paraam',
          'AG Weligamage', 'AJ Hall', 'AJ Tye', 'AK Kitchen', 'AM Fernando', 'AM Hardie', 'AM Rajpurohit', 'AN Lascu',
          'AR Balla', 'AR Gandhi', 'AR Menon', 'AR Nurse', 'AR Odedara', 'AS Dean', 'AUKDS Kalugala', 'AZ Shah',
          'Aamer Ikram', 'Aarnav Patel', 'Abu Hider', 'Abu Jayed', 'Adnan Mirza', 'Adnan Mufti', 'Ahsan Ali',
          'Ahsan ul Haq', 'Akif Raja', 'Ali Farasat', 'Ali Hussain', 'Ali Ivan', 'Ali Masood', 'Ali Muaaz',
          'Ali Rasool', 'Ali Waqar', 'Ali Yalmaz', 'Alok Kapali', 'Altaf Gill', 'Amir Ali', 'Amjad Gul', 'Andre Jarju',
          'Aphsal Ashraf', 'Apon Mustafizur', 'Arsalan Ahmed', 'Arslan Ahmed', 'Aryan Lakra', 'Asad Mohammad',
          'Ashfaq Ahmed', 'Asim Ashraf', 'Asrar Ahmed', 'Atif Rasheed', 'Avesh Khan', 'Awais Zia', 'Ayyaz Qureshi',
          'Aziz Mohammad', 'Azmat Ali', 'B Fernando', 'B Isaac', 'B Terbish', 'BA Parchment', 'BA Viraliliu',
          'BAD Manenti', 'BJ Dwarshuis', 'BJ Hodge', 'BJ Rohrer', 'BKB Corbin', 'BM Tickner', 'BM Wheeler', 'BN Toube',
          'BOP Fernando', 'BV Sears', 'Bashir Ahmad', 'Basiru Jaye', 'Bilal Aftab', 'Bilawal Bhatti', 'C Bayraktar',
          'C Green', 'CAH Stevenson', 'CAK Rajitha', 'CB Mpofu', 'CBRLS Kumara', 'CD Barnwell', 'CJ Dala', 'CJ Green',
          'CL Cairns', 'CM Wright', 'CS Martin', 'Chaudhary Akram', 'Chirag Suri', 'D Gim', 'D Johnson', 'D Kalvin',
          'D Kegasitswe', 'D Mogan', 'D Murphy', 'D Nikolov', 'D Sheeli', 'D Simpson', 'DA Rankin', 'DC Drakes',
          'DE Bernard', 'DF Jacobs', 'DGAPD Wiswi', 'DL Maddy', 'DP Michael', 'DR Brown', 'DR Mousley', 'DS Bajwa',
          'Danish Aziz', 'Deng Jinqi', 'E Beukes', 'E Bhonkar', 'E Kuyumcu', 'E Munkhbat', 'E Ochieng', 'EH Hutchinson',
          'Elias Hasan', 'Eric Phiri', 'F Campbell', 'FE Carava', 'FN Walsh', 'Farhan Ahmed', 'Fawad Ahmed',
          'Firas Hussain', 'G Burrows', 'G Coetzee', 'G Goudie', 'G Johnson', 'G Murali', 'G Venkateswaran',
          'G Wijekoon', 'GA Rogers', 'GB Hogg', 'GD McGrath', 'GHS Garton', 'GJ van Rensburg', 'GJP Kruger', 'GR Russ',
          'GS Ballance', 'Guido Angeletti', 'Gurdeep Singh', 'H Osinde', 'H Pile', 'H Rashid', 'H Satheedevi',
          'H Singh', 'H Virdee', 'HB Dickson', 'HB Shipley', 'HER Tyler', 'HH Dippenaar', 'HK Bennett', 'HL Harji',
          'HR Walsh', 'HV Patel', 'Hafiz Qaleem', 'Hazrat Luqman', 'Hussain Talat', 'Huzaif Yousuf', 'I Bardis',
          'I Uboh', 'I Wardlaw', 'IIR Bhana', 'IP Swaney', 'Iftekar Jaman', 'Ilyas Ataullah', 'Imran Butt',
          'Inam-ul-Haq', 'Inzamam-ul-Haq', 'Iqbal Hossain', 'Irfan Sarfraz', 'Isa Zaroo', 'Izhar Hussain', 'J Campbell',
          'J Essex', 'J Gumbie', 'J Jagroo', 'J Lewis', 'J Long', 'J Nyumbu', 'J Overton', 'JA Fitzgerald',
          'JA Richardson', 'JA Rudolph', 'JC Tredwell', 'JE Taylor', 'JH Kiani', 'JH Stander', 'JI de Villiers',
          'JJ Tucker', 'JKC Ahir', 'JMV Junior', 'JN Dorji', 'JN Gillespie', 'JNK Shannon', 'JP Behrendorff',
          'JS Henriksen', 'JS Malhotra', 'JS Patel', 'JW Dernbach', 'JW Hastings', 'JW Wilson', 'JWM Dalrymple',
          'JWN Moses', 'Jaison Jerome', 'Jasdeep Singh', 'Jason Lui', 'Jay Odedra', 'Jun Hyunwoo', 'Junaid Khan',
          'K Kekez', 'K Mendon', 'K Nagnama', 'K Nestor', 'K Pierre', 'K Sinclair', 'KA Bazil', 'KD Mehta', 'KK Ahmed',
          'KMA Paul', 'KOK Williams', 'KRP Silva', 'KT Maphaka', 'KY Wilfried', 'Kalyan Manne', 'Kamal Raiz',
          'Kamran Khan (2)', 'Kamran Wahid', 'Khalander Mustafa', 'Khawar Zafar', 'Khurram Shahzad', 'Kim Daeyeon',
          'Kuldeep Gurjar', 'L Gregory', 'L Louwrens', 'L Nou', 'L Wood', 'LB Williams', 'LK Sharma',
          'LP Kasturiarachchige', 'Lakshit Gupta', 'Lee Kangmin', 'Lucas Rossi', 'Lwin Maw', 'M Ansari', 'M Chadha',
          'M Faraz Akram', 'M Fontaine', 'M Gherasim', 'M Ibrahim', 'M Jenkinson', 'M Manivannan', 'M Ntini',
          'M Raikes', 'M Simmons', 'M Simpson-Parker', 'M Vijay', 'M Whelan', 'M van Lingen', 'MBS Jonkman', 'MC Alex',
          'MD Garratt', 'MJ Henry', 'MJ Ross', 'MJ Swepson', 'MJM Kavana', 'ML Kostic', 'ML Udawatte', 'MM Baig',
          'MO Bacarese', 'MP Vaughan', 'MS Kasprowicz', 'MS Panesar', 'MVT Fernando', 'MW Parkinson', 'Mazharul Islam',
          'Md Shafiqul Haque', 'Mohammad Ashraful', 'Mohammed Alamgir', 'Mohammed Awais', 'Mohammed Sameer',
          'Mominul Haque', 'Mudassar Muhammad', 'Mudassir Iqbal', 'Muhammad Asjed', 'Muhammad Babar', 'Muhammad Naeem',
          'Muhammad Younis', 'Muktar Ali', 'Mustapha Suwareh', 'N Burger', 'N Krishna', 'N Madziva', 'N Peter',
          'NA Karnik', 'NJ Astle', 'NM Carter', 'NM Lyon', 'NN Banner', 'NR Kirton', 'NR Welch', 'NT Gireesh',
          'NV Ojha', 'Naeem Gull', 'Naeem Islam', 'Najeeb Amar', 'Nauman Anwar', 'Nazimuddin', 'Niaz Ali',
          'Noorkhan Ahmedi', 'O Stewart', 'O Thomas', 'O Touray', 'OC McCoy', 'Omar Rassol', 'P Danci', 'P Desungnoen',
          'P Kerai', 'P Magafas', 'P Taylor', 'PA Hitchcock', 'PD Hennessy', 'PE Kruger', 'PJ Hughes', 'PKD Chase',
          'PR Brown', 'PRP Boissevain', 'PSP Handscomb', 'QF Djakaridja', 'Qalandar Khan', 'R Brar', 'R Cunningham',
          'R Davson', 'R Dhawan', 'R Dianish', 'R Drake', 'R Flannigan', 'R Francis', 'R Gunasekera', 'R Mahajan',
          'R Nil', 'R Olipa', 'R Tanna', 'R Theruvath', 'R Vishwanath', 'RGA Amah', 'RJ Gleeson', 'RK Kleinveldt',
          'RL Vitas', 'RM Scott', 'RR Emrit', 'RR Sarwan', 'RR Saun', 'RT Rubbi', 'RTM Mendis', 'Rafatullah Mohmand',
          'Raghav Dhawan', 'Rahel Khan', 'Ramanjot Singh', 'Rashid Khan', 'Raunaq Kapur', 'Riaz Afridi',
          'Rizwan Mangera', 'S Ateak', 'S Barnett', 'S Hongsi', 'S Joseph', 'S Mahmood', 'S Pokhriyal',
          'S Ramakrishnan', 'S Rengarajan', 'S Sengupta', 'S Snater', 'S Sohal', 'S Thakur', 'S Tosic', 'S Varathappan',
          'S Vesawkar', 'SA Abbott', 'SC van Schalkwyk', 'SD Parry', 'SD Valjalo', 'SDJJ Dima', 'SF Nhavotso',
          'SG Borthwick', 'SG Mangela', 'SHA Rance', 'SK Springer', 'SKDT Madusanka', 'SL Clephane', 'SP Guzman',
          'SR Patel', 'SR Tendulkar', 'ST de Silva', 'STR Binny', 'STRA de Silva', 'SW Masakadza',
          'Sachin Ganpat Shinde', 'Saeed Ahmed', 'Sajid Khan Afridi', 'Salvin Stanly', 'Samader Shadab',
          'Samiullah Rahmani', 'Sandeep Sharma', 'Sanjay Kumar', 'Saqlain Arshad', 'Sarfaraj Patel', 'Shahrukh Quddus',
          'Shamsudheen Purat', 'Shamsullah Ehsan', 'Shan Siddiqui', 'Shenjian Zheng', 'Shivam Mavi', 'Simranjit Singh',
          'Sinan Khan', 'Sohag Gazi', 'Suhrawadi Shuvo', 'Sukhdeep Singh', 'Sumit Singh', 'T Bukenya', 'T Langa',
          'T Parima', 'T Ritawa', 'T Sangha', 'T Shanmugam', 'T Taibu', 'T Ulutuna', 'T Wuatai', 'T Yotharat',
          'T Zotos', 'TD Astle', 'TG Thamae', 'TL Best', 'TL Cutler', 'TM Anker', 'TO Thilappan', 'TS Braat',
          'Tafseer Ali', 'Tashi Dorji', 'Tauqeer Hussain', 'UT Yadav', 'UWMBCA Welegedara', 'Umran Malik',
          'Usman Limbada', 'Utkarsh Srivastava', 'V Balakrishnan', 'V Hampihallikar', 'V Pulibanti', 'V Rathinasamy',
          'V Ravindran', 'V Shankar', 'VC Ahir', 'VM Vaghela', 'VN Veetil', 'Vinod Kumar', 'W Dlamini', 'W Kokaua',
          'W Viraliliu', 'WJ Lubbe', 'Wasim Ali', 'Xie Kunkun', 'Y Divekar', 'YSD Seneveratne', 'Yadwinder Singh',
          'Yash Singh', 'Yasir Mohammad', 'Yasser Nazir', 'Yogev Nagavkar', 'Z Arinaitwe', 'Zaheer Maqsood',
          'Zahid Abbas', 'Zahid Hussain', 'Zawar Farid', 'Zeerak Chughtai', 'Aftab Ahmed', 'Muhammad Amin', 'Adil Butt',
          'Sandeep Goud']
import streamlit as st
import pandas as pd
import pickle
import numpy as np
r
import streamlit as st
import pandas as pd
import pickle
import numpy as np
import random

# Load the trained model and data files
with open("rf_pipeline_22.pkl", "rb") as f:
    rf_pipeline = pickle.load(f)

player_stats_recent = pd.read_pickle("player_recent_statistics.pkl")
head_to_head_stats = pd.read_pickle("head_to_head_stats.pkl")
venue_stats = pd.read_pickle("venue_stats.pkl")

# Predefined data for players and teams
teams = ["India", "South Africa", "Australia", "England", "West Indies","Sri Lanka","Pakistan","Bangladesh","Newzealand"]
team_players = {
    "India": ['AR Patel', 'Abhishek Sharma', 'Arshdeep Singh', 'Avesh Khan',
              'CV Varun', 'DJ Hooda', 'DL Chahar', 'Dhruv Jurel', 'HH Pandya',
              'HV Patel', 'Ishan Kishan', 'JJ Bumrah', 'JM Sharma', 'KK Ahmed',
              'Kuldeep Yadav', 'M Prasidh Krishna', 'MP Yadav', 'Mohammed Siraj',
              'Mukesh Kumar', 'Nithish Kumar Reddy', 'R Parag', 'R Sai Kishore',
              'RA Jadeja', 'RA Tripathi', 'RD Gaikwad', 'RG Sharma', 'RK Singh',
              'RR Pant', 'Ramandeep Singh', 'Ravi Bishnoi', 'S Dube', 'SA Yadav',
              'SS Iyer', 'SV Samson', 'Shahbaz Ahmed', 'Shivam Mavi',
              'Shubman Gill', 'TU Deshpande', 'Tilak Varma', 'Umran Malik',
              'V Kohli', 'Washington Sundar', 'YBK Jaiswal', 'YS Chahal'],
    "South Africa": ["A Nortje", "BC Fortuin", "D Brevis", "D Ferreira", "T Bavuma", "WD Parnell",
                     "AK Markram", "DA Miller", "H Klaasen", "K Rabada", "KA Maharaj"],
    "Australia": ['A Zampa', 'AC Agar', 'AJ Turner', 'AM Hardie', 'BJ Dwarshuis',
                  'BR McDermott', 'C Connolly', 'C Green', 'CJ Green', 'DA Warner',
                  'GJ Maxwell', 'J Fraser-McGurk', 'JP Behrendorff', 'JP Inglis',
                  'JR Hazlewood', 'JR Philippe', 'KW Richardson', 'MA Starc',
                  'MP Stoinis', 'MR Marsh', 'MS Wade', 'MW Short', 'NT Ellis',
                  'PJ Cummins', 'RP Meredith', 'SA Abbott', 'SH Johnson',
                  'SPD Smith', 'T Sangha', 'TH David', 'TM Head', 'XC Bartlett'],
    "England": ['AAP Atkinson', 'AU Rashid', 'BA Carse', 'BM Duckett', 'CJ Jordan',
                'CR Woakes', 'DJ Malan', 'DR Mousley', 'HC Brook', 'J Overton',
                'JA Turner', 'JC Archer', 'JC Buttler', 'JG Bethell',
                'JM Bairstow', 'JM Cox', 'L Wood', 'LS Livingstone', 'MA Wood',
                'MM Ali', 'PD Salt', 'RJW Topley', 'Rehan Ahmed', 'S Mahmood',
                'SM Curran', 'TS Mills', 'WG Jacks'],
    "West Indies": ['A Athanaze', 'AD Russell', 'ADS Fletcher', 'AJ Hosein',
                    'AS Joseph', 'BA King', 'E Lewis', 'FA Allen', 'G Motie',
                    'HR Walsh', 'J Charles', 'JO Holder', 'KR Mayers', 'MW Forde',
                    'N Pooran', 'O Thomas', 'OC McCoy', 'OF Smith', 'R Powell',
                    'R Shepherd', 'RA Reifer', 'RL Chase', 'S Joseph', 'SD Hope',
                    'SE Rutherford', 'SK Springer', 'SO Hetmyer', 'SS Cottrell',
                    'T Hinds'],
    "Sri Lanka" : ['A Dananjaya', 'AD Mathews', 'AM Fernando', 'B Fernando',
       'BKG Mendis', 'C Karunaratne', 'C Wickramasinghe', 'CAK Rajitha',
       'CBRLS Kumara', 'D Madushanka', 'DM de Silva', 'DN Wellalage',
       'KIC Asalanka', 'M Pathirana', 'M Theekshana', 'MD Shanaka',
       'MDKJ Perera', 'MNK Fernando', 'N Thushara', 'P Nissanka',
       'PBB Rajapaksa', 'PHKD Mendis', 'PM Liyanagamage', 'PVD Chameera',
       'PWH de Silva', 'RTM Mendis', 'S Samarawickrama', 'WIA Fernando'],
    "Pakistan" : ['Aamer Jamal', 'Abbas Afridi', 'Abrar Ahmed', 'Agha Salman',
       'Arafat Minhas', 'Arshad Iqbal', 'Asif Ali', 'Azam Khan',
       'Babar Azam', 'Faheem Ashraf', 'Fakhar Zaman', 'Haider Ali',
       'Haris Rauf', 'Hasan Ali', 'Haseebullah Khan', 'Iftikhar Ahmed',
       'Ihsanullah', 'Imad Wasim', 'Irfan Khan', 'Jahandad Khan',
       'Khushdil Shah', 'Mirza Baig', 'Mohammad Amir', 'Mohammad Haris',
       'Mohammad Nawaz', 'Mohammad Rizwan', 'Mohammad Wasim',
       'Naseem Shah', 'Omair Yousuf', 'Qasim Akram', 'Rohail Nazir',
       'Sahibzada Farhan', 'Saim Ayub', 'Shadab Khan',
       'Shaheen Shah Afridi', 'Shan Masood', 'Sufiyan Muqeem',
       'Tayyab Tahir', 'Usama Mir', 'Usman Khan', 'Zaman Khan'],
    "Bangladesh" : ['Afif Hossain', 'Hasan Mahmud', 'Hasan Murad', 'Jaker Ali',
       'Liton Das', 'Mahedi Hasan', 'Mahmudul Hasan Joy', 'Mahmudullah',
       'Mehedi Hasan Miraz', 'Mohammad Saifuddin', 'Mrittunjoy Chowdhury',
       'Mustafizur Rahman', 'Nasum Ahmed', 'Nazmul Hossain Shanto',
       'Parvez Hossain Emon', 'R Mondol', 'Rakibul Hasan',
       'Rishad Hossain', 'Rony Talukdar', 'Saif Hassan',
       'Shahadat Hossain', 'Shakib Al Hasan', 'Shamim Hossain',
       'Shoriful Islam', 'Soumya Sarkar', 'Sumon Khan', 'Tanvir Islam',
       'Tanzid Hasan', 'Tanzim Hasan Sakib', 'Taskin Ahmed',
       'Towhid Hridoy', 'Yasir Ali Chowdhury', 'Zakir Hasan'],
    "New Zealand" : ['A Ashok', 'AF Milne', 'BG Lister', 'BM Tickner', 'BV Sears',
       'CE McConchie', 'CJ Bowes', 'D Cleaver', 'D Foxcroft',
       'DJ Mitchell', 'DP Conway', 'FH Allen', 'GD Phillips',
       'HB Shipley', 'HM Nicholls', 'IS Sodhi', 'JA Clarkson', 'JA Duffy',
       'JDS Neesham', 'KA Jamieson', 'KS Williamson', 'LH Ferguson',
       'MG Bracewell', 'MJ Hay', 'MJ Henry', 'MJ Santner', 'MS Chapman',
       'R Ravindra', 'TA Blundell', 'TA Boult', 'TB Robinson',
       'TG Southee', 'TL Seifert', 'TWM Latham', "W O'Rourke", 'WA Young',
       'ZGF Foulkes']
}

# Title
st.title("🏏Yash's  Dream11 Team Selector")

# Sidebar Inputs
st.sidebar.header("Match Setup")
pitch_type = st.sidebar.selectbox("Select Pitch Type", ["Green", "Flat", "Dusty", "Bouncy", "Other"])
weather_conditions = st.sidebar.selectbox("Select Weather Conditions", ["Sunny", "Windy", "Overcast", "Humid"])
venue = st.sidebar.selectbox("Enter Venue", venue_stats['venue'].unique())

# Team Selection
team_a = st.sidebar.selectbox("Select Team A", teams)
team_b = st.sidebar.selectbox("Select Team B", [team for team in teams if team != team_a])

# Player Selection
team_a_players = st.sidebar.multiselect(f"Select Playing XI for {team_a}", team_players[team_a])
team_b_players = st.sidebar.multiselect(f"Select Playing XI for {team_b}", team_players[team_b])

# Validate Player Selection
if len(team_a_players) != 11 or len(team_b_players) != 11:
    st.error("Please select exactly 11 players for both Team A and Team B.")
    st.stop()

# Combine Teams into DataFrame
selected_players = pd.DataFrame({'player': team_a_players + team_b_players, 'team': [team_a] * 11 + [team_b] * 11})

# Ensure required columns exist
required_columns = ['total_runs', 'balls_faced', 'boundaries', 'sixes', 'strike_rate',
                    'batting_average', 'total_wickets', 'balls_bowled', 'lbw', 'bowled',
                    'runs_conceded', 'economy', 'bowling_average', 'catches_total',
                    'runouts_total', 'stumps_total', 'caught_and_bowled', 'catch_wickets', 'role', 'team']

for col in required_columns:
    if col not in player_stats_recent.columns:
        player_stats_recent[col] = 0 if col in required_columns[:-2] else "Unknown"

# Filter selected player stats
player_stats = player_stats_recent[player_stats_recent['player'].isin(selected_players['player'])]

# Predict Fantasy Points
player_stats['predicted_points'] = rf_pipeline.predict(player_stats[required_columns])

# Generate 3 Different Teams
num_teams = 3
teams = []

for _ in range(num_teams):
    team = player_stats.sample(n=11, weights=player_stats['predicted_points'], random_state=random.randint(1, 1000))
    teams.append(team)

# Assign Trump Card Player
for team in teams:
    trump_card = team.iloc[len(team) // 2]  # Middle player in ranking
    team['is_trump_card'] = team['player'] == trump_card['player']

# Probabilistic Captain & Vice-Captain Selection
for team in teams:
    top_5_candidates = team.head(min(5, len(team)))  # Ensure at least 5 players available
    if len(top_5_candidates) == 0:
        continue

    probabilities = [0.4, 0.3, 0.2, 0.1, 0.05][:len(top_5_candidates)]  # Adjust probability size

    captain = random.choices(top_5_candidates['player'].tolist(), weights=probabilities, k=1)[0]
    team['is_captain'] = team['player'] == captain

    vice_captain_candidates = top_5_candidates[top_5_candidates['player'] != captain]
    if len(vice_captain_candidates) > 0:
        vice_captain = random.choices(vice_captain_candidates['player'].tolist(), weights=probabilities[1:], k=1)[0]
        team['is_vice_captain'] = team['player'] == vice_captain
    else:
        team['is_vice_captain'] = False

# Display Teams
#st.subheader("Optimized Dream11 Teams")
st.subheader("మీ పైసల్ పోతే నాకు తెల్వదు కానీ మీకు కోటి రూపాయాలు వస్తే నాకు సగం")
for i, team in enumerate(teams, start=1):
    st.write(f"### Team {i}")
    st.dataframe(team[['player', 'team', 'role', 'predicted_points', 'is_trump_card', 'is_captain', 'is_vice_captain']])
# Pitch Type Recommendations
pitch_recommendations = {
    "Green": "✅ This pitch favors **Bowlers**, especially fast bowlers.",
    "Flat": "✅ This pitch favors **Batters**, making it a high-scoring game.",
    "Dusty": "✅ This pitch supports **Spinners** and **All-Rounders**.",
    "Bouncy": "✅ This pitch helps **Fast Bowlers** with extra pace and bounce.",
    "Other": "✅ This pitch has a **neutral effect**, favoring all players equally."
}

# Weather Recommendations
weather_recommendations = {
    "Sunny": "☀️ **Good conditions for Batters**. The ball comes onto the bat nicely.",
    "Windy": "🌬️ **Favors Fast Bowlers**. Swing bowlers will be more effective.",
    "Overcast": "☁️ **Favors Swing & Seam Bowlers**. The ball will move a lot in the air.",
    "Humid": "🌡️ **Helps Spinners & Swing Bowlers** due to moisture in the air."
}
# Display Pitch Recommendation
st.subheader("🏟️ Pitch Type Impact")
st.write(pitch_recommendations[pitch_type])

# Display Weather Recommendation
st.subheader("🌦️ Weather Impact")
st.write(weather_recommendations[weather_conditions])
